### ISSUE TITLE
URP depth priming modeをauto or forceにすると輪郭線が消える

### ISSUE THREAD

**Issue by masak2** [lilxyzw/lilToon#100]
Unity2022.3.0 liltoon1.4.0
<img width="457" alt="スクリーンショット 2023-06-19 110813" src="https://github.com/lilxyzw/lilToon/assets/666025/6db39adf-0d21-479a-bb28-81895920ad1f">

タイトル通り、設定変えると輪郭線が描画されないバグです
unity2021でも発生します

**Comment by lilxyzw** [comment]
It is not fixed for this reason.
https://github.com/lilxyzw/lilToon/issues/54#issuecomment-1304429107
