### ISSUE TITLE
Outline missing on Unity URP Forward

### ISSUE THREAD

**Issue by bc15bekl** [lilxyzw/lilToon#102]
As of 2022 LTS, outline is completely missing on Unity URP Forward render setting. On 2021 LTS, it was possible to get the outline to show using "Cutout" or transparency but now, it doesn't show up at all.

**Comment by masak2** [comment]
https://github.com/lilxyzw/lilToon/issues/100
same issue, Depth Priming Mode "Disabled" is going to solve.

**Comment by bc15bekl** [comment]
The problem is fixed by setting the renderer queue to 3000.
