### ISSUE TITLE
Gemにマスクをあてたい

### ISSUE THREAD

**Issue by ishiiyuki** [lilxyzw/lilToon#110]
Gemに、マスク画像を設定してエミッションマスクみたいにマスク画像の白いところだけGemにしたいと相談が来てたので
こちらでIssueにさせてもらいました。
対応予定はありますでしょうか？

**Comment by lilxyzw** [comment]
こちらはGemシェーダーのみ描画方法が他バリエーションと全く異なり、対応させる場合はパスの追加が必要になってしまうため申し訳ないですが対応予定はありません。

**Comment by ishiiyuki** [comment]
Misskeyの方で教わった流れで、調査とローカルで対応やってみます。
