### ISSUE TITLE
全materialのmigrationを手動で発生させれるようにする

### ISSUE THREAD

**Issue by anatawa12** [lilxyzw/lilToon#112]
assetをimportしたとき等にgit管理の都合で手動で実行したいことがあります

**Comment by lilxyzw** [comment]
シェーダー設定内にスタートアップ時にmigrationを行うかどうかの設定と、手動でmigrationを行う`Assets/lilToon/[Material] Run migration`メニューを追加しました。こちらは1.5.0で反映いたします。
