### ISSUE TITLE
質問・影色のLUTってどんな機能？

### ISSUE THREAD

**Issue by ni1chigo2115** [lilxyzw/lilToon#116]
影色のLUTという機能の効能がよくわからないのですが、どういう機能なのでしょうか
PoiyomiやLutの項目には影色グラデーションファイルを指定する項目があり
それを指定して影を選択する形でした
（これはXiexeにも同じものがあります）
Liltoonは3色を指定する形ですが、各影色の挙動をもう少し細かく指定できます
しかしLUTというのがどういう効果を表すのかがマニュアルを読んでもわからなかったので、聞いてみました

**Comment by lilxyzw** [comment]
Unreal Engineのドキュメントになりますが、LUTはこのようなテクスチャになっています。
https://docs.unrealengine.com/4.27/ja/RenderingAndGraphics/PostProcessEffects/UsingLUTs/

lilToonではこの仕組みを影に対して適用し、色調補正で作成した影色と同じような色をシェーダー上でも出せるようにしています。

**Comment by ni1chigo2115** [comment]
ありがとうございます、あくまで同じような影色というだけで、LUTテクスチャーを流用できるわけではないみたいですね
