### ISSUE TITLE
MLShader

### ISSUE THREAD

**Issue by kogepandur** [lilxyzw/lilToon#118]
バグ: MLshader not showing up under liltoon and Materials using MeltyLily settings don't work
再現方法: 

# 可能であれば
Unityバージョン: 2019.4.31.f1
lilToonバージョン: 1.4.1
VRChatのワールド: 
スクリーンショット: 
コンソールログ:
![Screenshot 2023-09-17 205613](https://github.com/lilxyzw/lilToon/assets/145312751/084dd257-aa22-48f1-89b1-4fac87012774)
![Screenshot 2023-09-17 205704](https://github.com/lilxyzw/lilToon/assets/145312751/6a7b4255-911c-4e74-86f3-1663eb5551a4)

**Comment by lilxyzw** [comment]
When I tested it, the material thumbnail turned magenta, but the shader itself seemed to work well. If you are too, the material thumbnail will be fixed on reimport.
