### ISSUE TITLE
鏡の中判定が甘い

### ISSUE THREAD

**Issue by momoma-null** [lilxyzw/lilToon#12]
https://github.com/lilxyzw/lilToon/blob/e1b23f44e7bb17942d5aa64db452cde15d7be83a/Assets/lilToon/Shader/Includes/lil_common_macro.hlsl#L1426
正面を向くと判定に失敗する可能性があります。以下のようにV行列の座標系が左手系か右手系かで判定したほうが正確かと思われます。
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/release/urp/2.5.0/Runtime/Shaders/UniversalToonBody.hlsl#L393-L394

**Comment by lilxyzw** [comment]
テスト用のシェーダーを作成してCameraのRotationのxyいずれかが0であるときに判定に失敗することを確認いたしました。
現在はミラー判定を使用していないので影響はないですが、改変シェーダーで使用される可能性を想定して次回バージョンにて修正を加えます。

**Comment by lilxyzw** [comment]
バージョン1.2.11にて座標系を元に判定するように修正を加えました。
https://github.com/lilxyzw/lilToon/blob/1ac723c03f617f3b876a186a59d755cbefe849a4/Assets/lilToon/Shader/Includes/lil_common_macro.hlsl#L1433
