### ISSUE TITLE
MToon変換を外部のエディタスクリプトから呼び出したい

### ISSUE THREAD

**Issue by kaikoga** [lilxyzw/lilToon#124]
こんにちは。アバター内のマテリアルについて、VRM用に変換されたマテリアルを一括で作成するツールの制作を考えています。
外部のC# のEditor ScriptからlilToonのMToon変換機能にアクセスできると嬉しいです。

**Comment by lilxyzw** [comment]
マテリアルの変換処理がマテリアルエディタに強く依存していたため時間がかかってしまいましたが、マテリアルエディタから変換処理を分離して外部から呼び出せるようにしました。こちらの変更は次のバージョンから利用できるようになります。
https://github.com/lilxyzw/lilToon/blob/f80e1f13f385c1774a6626cb585a4ab6f5728caa/Assets/lilToon/Editor/lilMaterialBaker.cs#L774
