### ISSUE TITLE
Cutout material with outline fills in full mesh on other side

### ISSUE THREAD

**Issue by Lavasteam-Ariz** [lilxyzw/lilToon#126]
![image](https://github.com/lilxyzw/lilToon/assets/61638102/344b0ec6-fd6e-4340-af3c-4a90246d4f15)

 I don't know how to explain, but whenever I use an outline with the material, it fills in the rest of the mesh from the other side. This issue does not occur with Poi Toon

**Comment by lilxyzw** [comment]
If you set the same texture as the main texture for the outline, or set another texture with transparency, it will become transparent.
