### ISSUE TITLE
Baking albedo with a Gradation Map doesn't work

### ISSUE THREAD

**Issue by IlexisTheMadcat** [lilxyzw/lilToon#127]
![image](https://github.com/lilxyzw/lilToon/assets/50256109/bd3bbdc2-68a6-44d4-bf62-83b6f6f21bec)

I wanted to add an outfit for an avatar, but because the shader settings they provided uses a Gradation Map instead of color adjustments, I can't bake the texture for use on Quest. Recreating the effect with my photoshop accurately would be difficult.

lilToon 1.4.1

**Comment by lilxyzw** [comment]
It seems that the change in the gradation map was ignored and the warning was issued. Since it was fixed in the development branch, it will be reflected in the next version.
