### ISSUE TITLE
マテリアル複数選択で描画モードを変更しても先頭の1マテリアルしか切り替わらない

### ISSUE THREAD

**Issue by whiteflare** [lilxyzw/lilToon#135]
lilToon1.4.1にて確認

マテリアルを複数選択して描画モードを変更しても、先頭の1マテリアルしか変更されませんでした。
![e8e642548113ea2a8e042b9112deff94](https://github.com/lilxyzw/lilToon/assets/44968974/436ee218-68e6-4028-90ba-871039a09c8f)
先頭の1マテリアルのみ変わるため、インスペクタ上では複数編集状態になります。
![image](https://github.com/lilxyzw/lilToon/assets/44968974/3b96e36f-e2a4-404e-9164-56d2615c9124)

あるべき結果としては、選択した全てのマテリアルの描画モードが変更されることと思います。

**Comment by lilxyzw** [comment]
ご報告ありがとうございます。devブランチにて選択中の全てのマテリアルを一括で描画モードを変更できるように修正しました。こちらは1.5.0にて反映いたします。
