### ISSUE TITLE
カスタムシェーダーのマテリアルを VRCSDK でビルドすると UnityEditor がクラッシュする

### ISSUE THREAD

**Issue by kb10uy** [lilxyzw/lilToon#142]
## 概要
* Unity 2022.3.6f1 / VRCSDK 3.5.0 / lilToon 1.5.0 の環境で、カスタムシェーダー機能を使っているマテリアルが含まれているとアバターのビルド中にエディタがクラッシュします。
    - 含まれている場合は必ずクラッシュし、標準の lilToon に差し替えるとビルドできるようになります。
    - プロジェクトにカスタムシェーダーのマテリアルが含まれているだけではクラッシュしません。
* クラッシュすることが確認できたカスタムシェーダー
    - ドキュメント内使用例の [lilToonGeometryFX 1.0.1](https://lilxyzw.github.io/lilToon/#/en-us/dev/custom_shader?id=%e4%bd%9c%e4%be%8b)
    - [liltoon-msdfmask 1.5.0-p6](https://github.com/kb10uy/liltoon-msdfmask)

## 再現手順
1. 上記環境で新規アバタープロジェクトを作成する。
2. プロジェクトを開いて lilToonGeometryFX をインポートする。
3. アバターとして認識される GameObject を構成して、その内のメッシュに上記サンプルのマテリアルを割り当てる。
4. Build & Test を実行するとクラッシュする。

<hr>

[プロジェクト内 Logs のログ](https://gist.github.com/kb10uy/65452ced4db4fce55ae1a194fd93028a)

追記: LILTOON_DISABLE_OPTIMIZATION でビルド可能

**Comment by lilxyzw** [comment]
こちらのクラッシュは[Unityのバグ](https://issuetracker.unity3d.com/issues/crash-on-malloc-internal-when-recompiling-a-shadergraph-used-by-another-shader-via-usepass)が原因で、VRCSDKの指定を無視してUnity 2022.3.15f1を使用することでクラッシュしなくなります。UsePassを使わない以外の回避方法が無く、UsePassを使わない場合は大量のシェーダーがコンパイルされて遅くなります。そのため、問題の発生するUnityのバージョンでは強制的に最適化を無効化する形で対応しようかと考えています。

**Comment by galister** [comment]
devブランチの話ですが、Unity2022のLinux版でアバターをアップロードできても、ゲーム内はUnlitシェーダーになっています。

Windowsの方は、カスタムシェーダーはゲーム内でも正しく表示されていますか？
