### ISSUE TITLE
Liltoon only draws shadows for directional light, and does not draw shadows for other light sources.

### ISSUE THREAD

**Issue by sakada3** [lilxyzw/lilToon#147]
![image](https://github.com/lilxyzw/lilToon/assets/10657819/a8db95d0-fd96-4505-a4be-416af45bfd23)
spot light example

https://github.com/lilxyzw/lilToon/assets/10657819/b03df0e9-4eb4-42a6-bbb2-9aee1b560dd8

directional light example

on liltoon version 1.3.6, 1.4.1, 1.5.0
same bias, same shader settings.
what can i do?

**Comment by lilxyzw** [comment]
This is according to specifications. If a shadow is drawn using anything other than the main light (directional light), the shadow will be dark and dirty.
