### ISSUE TITLE
Template Shader + Point Lights

### ISSUE THREAD

**Issue by galister** [lilxyzw/lilToon#15]
LilToon 1.2.11 + https://github.com/lilxyzw/lilToon/raw/Document/files/Template.zip
Unity 2019.4.31f1

The `TemplateFull` shader from the Template.zip above breaks near point lights.
The contents of the template folder weren't changed, this is a fresh import.

I tried deleting the `Assets/lilToon` and `Assets/lilToolSetting` folders and reimporting 1.2.11 from the unitypackage.

Here's a video comparing the template shader to the one from the freshly imported unitypackage:
https://streamable.com/7vi6fz

Affects the regular shader as well as lite and multi.

When exporting the preprocessed `ltspass_opaque.shader` from the `ltspass_opaque.lilcontainer` via the unity inspector, there seems to be some weirdness in the ForwardAdd pass:
```
            #define LIL_PASS_FORWARDadd
```
this should probably be `LIL_PASS_FORWARDADD`?

For the full file:
[ltspass_opaque.shader.txt](https://github.com/lilxyzw/lilToon/files/8380224/ltspass_opaque.shader.txt)

**Comment by lilxyzw** [comment]
Thank you for reporting the bug.
There was a problem with the order of processing the text.
It will be fixed by modifying the script in [this way](https://github.com/lilxyzw/lilToon/commit/d64f406b0c04026eee7ba3d9ef32f5737f48eb47) and re-importing the shader.
This fix will be applied in the next version

**Comment by lilxyzw** [comment]
This bug has been fixed in version 1.2.12.
https://github.com/lilxyzw/lilToon/releases/tag/1.2.12
