### ISSUE TITLE
VRChat のアバターで Material と Material Variant が混在すると見た目が混じる

### ISSUE THREAD

**Issue by nekobako** [lilxyzw/lilToon#150]
VRChat のアバターに  lilToon の Material と Material Variant が混在していると、Material Variant 側の見た目に Material 側の見た目が混じります。

再現手順です。
1. 下記の Material と Material Variant を作成します
  - Red: lilToon のメインカラーを赤にした Material
  - Blue: lilToon のメインカラーを青にした Material
  - BlueVariant: Blue マテリアルの Material Variant (Override 無し)
2. 下記の構成のアバターを作成します
- AvatarRoot
  - CubeRed (Red マテリアルを設定した Cube)
  - CubeBlue (BlueVariant マテリアルを設定した Cube)
3. Unity Editor 上では赤の Cube と青の Cube が表示されますが、VRChat 上では両方とも赤の Cube に見えます

混じると書いたのは、例えば上記の Red マテリアルに輪郭線を設定したとすると、 CubeRed は輪郭線ありの赤い Cube になりますが、CubeBlue は輪郭線なしの赤い Cube に見えるためです。
シェーダの違いはそのままで同名のプロパティが混じるような挙動に感じます。

Unity か VRChat のバグな気もしますが、Standard シェーダおよび UnlitWF シェーダでは発生しなかったためこちらにて報告させていただきました。

(Unity 2022.3.6f1 と Unity 2022.3.15f1 で確認)

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。1.5.1にてビルド時の最適化で再帰的にparentのマテリアルを参照するようにしたのでおそらく正しく描画されるようになったと思われます。

**Comment by nekobako** [comment]
修正確認できました！ご対応ありがとうございますｍｍ
