### ISSUE TITLE
ミラーモードで片方のみのとき，Unityでの表示とVRChatでの表示が異なる

### ISSUE THREAD

**Issue by ito415** [lilxyzw/lilToon#151]
VRChatのアバターにlilToonのマテリアルを用いてメインカラー2ndでデカール化をした際に，ミラーモードで片方のみを選択している場合でもVRChatでは両方に表示されます．

Unity
![image](https://github.com/lilxyzw/lilToon/assets/71802262/87f99450-7660-42e4-abea-4b7dfd36f826)

VRChat
![image](https://github.com/lilxyzw/lilToon/assets/71802262/90429211-77e0-42e4-994f-217dfe17e28c)

なんとなく原因は分かっているので不具合というか質問です．

再現方法
1. 左右のUVが同じ場所に配置されているアバターを用意
2. メインカラー2ndにてデカール化にチェック
3. ミラーモードを右のみ・反転にする
4. VRChatにアップロードして確認する．

多分UVが左右で同じ場所に配置されているのが原因なんだろうなと思うんですが，
デカール化で片方だけ表示させることは難しいのでしょうか．

よろしくお願いいたします．

Unityバージョン: 2022.3.6ｆ１
lilToonバージョン: 1.5.0

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。こちらはメッシュから必要な情報を消してしまうUnityの不具合で、おそらくlilToon 1.5.2以降で回避できるようになったかと思われます。

**Comment by ito415** [comment]
早々のご対応ありがとうございました．
試してみます．
