### ISSUE TITLE
Please attach compiled lilcontainer source code to the asset as a TextAsset

### ISSUE THREAD

**Issue by SenkyDragon** [lilxyzw/lilToon#154]
Unity makes it hard to get the generated shader source code out of a Shader object. Please consider attaching the lilcontainer generated source to the asset in a TextAsset object, so that downstream users can read the source code for patching purposes.

Here is an example: https://github.com/orels1/orels-Unity-Shaders/blob/v6.3.0/Packages/sh.orels.shaders.generator/Editor/ShaderDefinitionImporter.cs#L573

(Currently, because this does not exist, we are forced to call `UnpackContainer` via reflection 😓 https://github.com/VRCFury/VRCFury/blob/main/com.vrcfury.vrcfury/Editor/VF/Builder/Haptics/SpsPatcher.cs#L565 )

**Comment by lilxyzw** [comment]
Thank you for the request! This feature has been supported since version 1.7.0.
