### ISSUE TITLE
(BUG? IDK) Undeclared identifier 'str' at Assets/lilToon/Shader/Includes/lil_common_vert.hlsl(33) (on d3d11)

### ISSUE THREAD

**Issue by AstraeaZero** [lilxyzw/lilToon#155]
All time im getting error when adding a custom property with Motchi Shader to Liltoon 1.6.0 in Unity 2022, on 1.4.1 2019 everything was working fine. I need report this to shader author for update?

**Comment by wataame89** [comment]
I am the author of Motchi Shader.
The issue here is a bug in my program, not in lilToon.
The latest version, ver1.9.0, should work fine.
