### ISSUE TITLE
Feature request: More main color slots for decals

### ISSUE THREAD

**Issue by imdempsey** [lilxyzw/lilToon#156]
I was wondering if it were possible to add a 4th Main Color slot on materials? In my case  I'm hoping to be able to add one more decal to my main body texture, but both Main Color 2nd and 3rd are used by two other decals.

マテリアルに4つ目のメインカラースロットを追加することは可能でしょうか？私の場合、メインボディのテクスチャにもう1つデカールを追加できればと思っているのですが、メインカラーの2番目と3番目は両方とも他の2つのデカールで使われています。

**Comment by Midorina** [comment]
Bump. This is seriously needed.
