### ISSUE TITLE
【Request】距離クリッピングキャンセラーの無効化の閾値の初期値を0.1から変更して欲しい

### ISSUE THREAD

**Issue by c-colloid** [lilxyzw/lilToon#16]
VRCユーザーのサポートを行っていて複数ワールドにおいてlilToonの距離クリッピングキャンセラーが正常に働いていないという報告をいただきました。

調べてみたところ、1.2.10以降で追加された無効化設定の初期値が　”0.1”　になってる事が原因ではないかと思います。
UnityのカメラのNearClipの初期値は　”0.3”　ですので、多くの所謂「ガチ恋距離」を想定していないワールドでは初期値のまま使われているのではないか、そのため距離クリッピングキャンセラーが無効化されていたのではないのかと考えました。
実際にUnity上では無効化の閾値を0.31に変更して初期カメラで問題が無くなったことを確認できました。

初期値から変更しているワールドで0.1”より小さく”しているワールドでは最初から「ガチ恋距離」を想定したNearClipを設定していると思われるので、この無効化設定の初期値ではVRCの状況に即していないのではないかと思います。

初期値を　”0.31以上”　で無効化するように変更していただけると初心者の方にも混乱を招きづらくなるのではないかと思います。

**Comment by lilxyzw** [comment]
ご連絡ありがとうございます。こちらの設定には以下の経緯があります。

## 無効化の閾値を追加した経緯
アバターに顔カメラ（自分を映すカメラ）を導入し、`NearClip`をあえて大きめに（0.25など）に設定することで撫でられているところを見やすく設定する場合があります。その場合に`距離クリッピングキャンセラー`が発動してしまうと意図に反してアバターが写り込んでしまうことになります。そこで意図に反した発動を防ぐために`NearClip`の閾値を設定することにしました。

## 閾値を`0.1`とした理由
Unity上でカメラの`NearClip`の初期値は0.3となっていますが、実際にワールドを作成しテストを行ったところ「`NearClip`が0.05以上に設定されていても強制的に0.05に変更される」という挙動を確認しました（`Reference Camera`は設定済みで、0.05より小さい値を設定したところ小さな値はそのまま使用されるようでした）。そこで、この挙動と前述の顔カメラの事情を考慮し`NearClip`の閾値を0.1としました。

## VRChat上で距離クリッピングキャンセラーが正常に動かない場合について
正常に動かないワールドが不明なため憶測になってしまいますが、以下のパターンが考えられます。

- ワールドが古いバージョンで作られたものであり、`NearClip`に0.05以上に値が使われてしまう
- クライアント側、またはワールド側の何らかの設定が影響し、`NearClip`が0.05以上になる場合がある
- シェーダー側になにかしら不具合があり、距離クリッピングキャンセラーがうまく動作しない

この問題は初期値を0.31以上とすることで解決する可能性もございますが、私が確認した顔カメラのケースでは`NearClip`の値を0.27としていたため、この閾値に設定してしまうと閾値追加前の問題が再度発生してしまう形となります。また、一部のワールドで発生する問題についてはUnity 2020移行時に解決する可能性もありますが、何か対策ができないか考えてみます。もし該当ワールドについて情報がございましたら、再度ご連絡いただければ幸いです。
