### ISSUE TITLE
UV Tile Discard でチェックボックスにチェックが付けられない

### ISSUE THREAD

**Issue by Ani-kun** [lilxyzw/lilToon#160]
Unity 2019.4.31f1 環境で UV Tile Discard のチェックボックスで X > 0 の箇所にチェックを付けられない
チェックを付けようとオンカーソルにすると横一列がハイライトされた状態になりクリックすると X = 0 の箇所にチェックが付く
Debug モードから直接 _UDIMDiscardRow0_1 を 1 にして動作したのでインスペクタのバグかもしれない
Unity 2022.3.6f1 環境では発生しない

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。先程1.7.2にてこちらの不具合を修正いたしましたので適宜アップデートをお願いします。
