### ISSUE TITLE
PSDテクスチャを焼き込むと正しいテクスチャが生成されない

### ISSUE THREAD

**Issue by zinntikumugai** [lilxyzw/lilToon#17]
https://github.com/kurotu/VRCQuestTools/issues/6 より来ました

バグ: 
PSDテクスチャを焼き込むと正しいテクスチャが生成されない

再現方法: 
1. PSDファイルをメインテクスチャに設定する
2. (メインテクスチャカラーが`FFFFFF`だと焼き込めないので)カラーを`FEFEFE`に変更
3. 最適化の`すべて焼き込み`を実行する
4. エラーに相当するものは出て来ないが8x8のテクスチャが生成される

![image](https://user-images.githubusercontent.com/16275962/166180352-273c8702-e753-48a5-afc7-a661d7d8b779.png)

検証アバター ：[RadDollV2](https://tonomaoo.booth.pm/items/3741802)

Unityバージョン: 元のissuesと重複するので省略
スクリーンショット: 

焼き込み後と前
![image](https://user-images.githubusercontent.com/16275962/166180530-26d87a0d-d581-43c3-8259-330b7f20a720.png)

コンソールログ: 

`すべて焼き込み`をした際出てきます
```
Releasing render texture that is set to be RenderTexture.active!
UnityEngine.Object:DestroyImmediate (UnityEngine.Object)
lilToon.lilToonInspector:TextureBake (UnityEngine.Material,int) (at Assets/lilToon/Editor/lilInspector.cs:10508)
lilToon.lilToonInspector:TextureBakeGUI (UnityEngine.Material,int) (at Assets/lilToon/Editor/lilInspector.cs:10056)
lilToon.lilToonInspector:DrawAllGUI (UnityEditor.MaterialEditor,UnityEditor.MaterialProperty[],UnityEngine.Material) (at Assets/lilToon/Editor/lilInspector.cs:3190)
lilToon.lilToonInspector:OnGUI (UnityEditor.MaterialEditor,UnityEditor.MaterialProperty[]) (at Assets/lilToon/Editor/lilInspector.cs:990)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

**Comment by lilxyzw** [comment]
ご連絡ありがとうございます。https://github.com/lilxyzw/lilToon/commit/3702d45d3213db71541c9987e728e56496335bf0 にてPSD使用時のベイク処理に対して修正を加えました。ベータ版のパッケージは[こちら](https://github.com/lilxyzw/lilToon/releases/tag/1.2.13beta)ダウンロードできます。

## 注意点
PNG/JPG以外のフォーマット使用時は生のテクスチャデータではなく、アセットとしてインポートされた後の圧縮されたテクスチャを使用するため、画質が劣化する場合があります。

## 不具合の詳細
[ImageConversion.LoadImage()](https://docs.unity3d.com/ja/current/ScriptReference/ImageConversion.LoadImage.html)がPNG/JPGのみのサポートとなっているため、他のフォーマットを使用していた場合に正しく読み込めなくなります。問題を回避するために拡張子が`.png` `.jpg` `.jpeg`であった場合のみ`LoadImage()`を使用、それ以外の場合はアセットをそのまま`Texture2D`として読み込む形にしました。ただしPNG/JPG以外はアセットとして圧縮後の画像を読み込むため、インポート設定次第で画質の劣化が想定されます。

**Comment by zinntikumugai** [comment]
対応ありがとうございます。

確認したところ問題なく変換できるようになりました。

> PNG/JPG以外のフォーマット使用時は生のテクスチャデータではなく、アセットとしてインポートされた後の圧縮されたテクスチャを使用するため、画質が劣化する場合があります。

こちらはテクスチャのインポート設定(MaxSizeやCompressionなど)の影響を受ける認識であっていますでしょうか？

**Comment by lilxyzw** [comment]
その認識で大丈夫です。例えば`Compression`が`Normal Quality`だった場合、その分の圧縮がされた状態でテクスチャ焼き込みが行われ、書き出されたテクスチャが更に圧縮によって劣化するという形になります。事前に`Max Size`を元のテクスチャの解像度以上に設定、`Compression`を`None`にした状態であれば劣化を最小限に抑えられます。

**Comment by zinntikumugai** [comment]
では今回追加していただいた機能としては、PSDを扱える環境ではない、触りたくない人向けで、劣化を気にする人やインポート設定をいじってる人はなるべく事前にPSDをPNG/JPGに変換したほうが良さそうですね。

問題箇所は解決したのでこちらのIssueは閉じます。
