### ISSUE TITLE
Screen Space Ambient Occlusion does not work with lilToon

### ISSUE THREAD

**Issue by leeshey** [lilxyzw/lilToon#171]
![image](https://github.com/lilxyzw/lilToon/assets/36664731/5288ed75-0fb8-4eee-97bd-3a4bb905ecc6)
This image shows _SSAO_OcclusionTexture, but avatar object using lilToon does not appear.
Do you have any solution for this?
Thanks!

**Comment by lilxyzw** [comment]
Since lilToon is a toon shader, SSAO is not reflected. This is because applying SSAO to the toon shader makes it look very bad.
