### ISSUE TITLE
Feature request: Decals for emission

### ISSUE THREAD

**Issue by Disappear9** [lilxyzw/lilToon#174]
Hi there:
Now we have decal for main color, I was wondering if it is possible to add decal for emission? It will be really convenient for making body tattoos or glowing hair.
Thank you.

MTL:
こんにちは：
メインカラー用のデカールができましたが、発光用のデカールを追加することは可能でしょうか？ボディタトゥーや光る髪にとても便利だと思います。
ありがとうございます。

**Comment by lilxyzw** [comment]
![image](https://github.com/lilxyzw/lilToon/assets/74490257/49d6bf8e-c386-4778-9df8-7ebb0ef1622a)
You can achieve the same effect as emission by simply not applying lighting to the decal. Set the blend mode to additive if necessary.

**Comment by Disappear9** [comment]
Thanks for the reply!
That's indeed an approximation way, but it will missing features like blink and fluorescence?
