### ISSUE TITLE
Problem with visual of the shader

### ISSUE THREAD

**Issue by MisakaChan95** [lilxyzw/lilToon#18]
Hello,
i dont really know if this Issue happened before.
![Issue](https://user-images.githubusercontent.com/105174848/167315233-6448d09b-f151-4211-abad-78930d258d92.png)

Clear is just that it has to do with the shader. I can not even describe it :) when i upgraded the original toon version it was looking "normal" But somehow it is looking like this again.
Can you maybe help me here?

**Comment by lilxyzw** [comment]
Thank you for reporting the bug.

# Bug Details
I am not certain, but it is possible that for some reason the material update did not work and the outlines were activated. I will work on getting this issue fixed.

# How to Fix
The outlines appear to be too large. Turning off the outlines or lowering the width sufficiently may fix this problem.
![outline](https://user-images.githubusercontent.com/74490257/167334791-37e0bc46-4328-4e52-aa45-72fb05131d4a.png)

**Comment by lilxyzw** [comment]
I think this problem has been fixed as there have been no other similar bug reports for several months. I will close this issue in a week if there are no further comments.
