### ISSUE TITLE
Change lanuage name in liltoon2

### ISSUE THREAD

**Issue by yelandiealma** [lilxyzw/lilToon#189]
In Liltoon 2, the original "繁體中文 / Chinese Traditional" has been changed to "中文(台湾) / Chinese Taiwan".
Taking into account user and political factors, I hope to keep it unchanged.

file name should be: zh-Hant
display name should be: 繁體中文 or 中文（繁體）

ps: https://github.com/bdunderscore/ndmf/issues/171

**Comment by Anteness** [comment]
I hope to keep them unchange too, also the language name "中文(中国)" was wrong.
It should be "简体中文" or "中文（简体）",  and the language code should be: zh-Hans
