### ISSUE TITLE
[QUESTION] What's csc.rsp?

### ISSUE THREAD

**Issue by anatawa12** [lilxyzw/lilToon#19]
When I add liltoon to my unity project, `Assets/csc.rsp` is generated.

1. What's the file for?
2. Should I track it with git? or ignore it?

**Comment by lilxyzw** [comment]
This is a file for using `System.Drawing` in GIF image conversion. It may be good to keep track of it with git as it may be generated or rewritten by other programs. There was not enough documentation for this file, so I will add it.
https://docs.unity3d.com/2021.3/Documentation/Manual/dotnetProfileAssemblies.html

**Comment by anatawa12** [comment]
Thank you.
