### ISSUE TITLE
Unity2022 3.22でfix lightingするとboundsがめちゃくちゃでかくなります

### ISSUE THREAD

**Issue by TAKUHIDE** [lilxyzw/lilToon#190]
liltoonは最新の1.7.3（vcc）です
最初は2019から移行したbugかと思ってたが
2022で新しいプロジェクトを作って試した結果同じbugありました
fix lightingするとboundsの数値が全部12.5になります
<img width="397" alt="{2402BEB7-1AF8-4961-B136-BF126E2D637B}" src="https://github.com/lilxyzw/lilToon/assets/65989971/3c1eeb91-e04a-49b3-9483-4e9bf5493387">

**Comment by TAKUHIDE** [comment]
しかもボンズの中心点も結構下の方に移動してます

**Comment by lilxyzw** [comment]
全く同じアバターを2019でFix Lightingするとbugは発生しなくなりますか？
