### ISSUE TITLE
UV Tile Discardで非表示にしたメッシュにリアルタイム影が映る

### ISSUE THREAD

**Issue by mimyquality** [lilxyzw/lilToon#191]
UV Tile Discardで非表示にしたメッシュにリアルタイム影が映りこみます。
対象のメッシュはReceive Shadowsが有効になっています。

元メッシュ(ジャケット)
![VRChat_2024-06-01_23-21-09 784_3840x2160 (中)](https://github.com/lilxyzw/lilToon/assets/86596687/cb8acd3f-5a29-4014-949d-80c59c1f7cd2)

影付きリアルタイムディレクショナルライトのあるワールドでメッシュを消した状態
![VRChat_2024-06-01_23-20-59 979_3840x2160 (中)](https://github.com/lilxyzw/lilToon/assets/86596687/9e1855bc-4414-417c-8003-0c119061b82f)

**Comment by anatawa12** [comment]
duplicate of https://github.com/lilxyzw/lilToon/issues/179?
