### ISSUE TITLE
Audiolinkの適用先「メインカラー2nd」「メインカラー3rd」が機能しない

### ISSUE THREAD

**Issue by Petanoco** [lilxyzw/lilToon#195]
Audiolinkの適用先の項目には「メインカラー2nd」「メインカラー3rd」の項目がありますが、これらが機能しません。メインカラー2ndを有効化した状態でこれらのチェックを入れても、メインカラー2ndの強度は1のまま固定されています。

2nd, 3rdテクスチャの処理がAudiolinkの処理より先に行われているため？
https://github.com/lilxyzw/lilToon/blob/b96470d3dd9092b840052578048b2307fe6d8786/Assets/lilToon/Shader/Includes/lil_pass_forward_normal.hlsl#L261-L282
https://github.com/lilxyzw/lilToon/blob/b96470d3dd9092b840052578048b2307fe6d8786/Assets/lilToon/Shader/Includes/lil_pass_forward_normal.hlsl#L401-L408

**Comment by prappe** [comment]
I experienced this issue as well on lilToon 1.7.3.
> 2nd, 3rdテクスチャの処理がAudiolinkの処理より先に行われているため？

You are correct, processing Main Color 2nd & 3rd after Audiolink fixes this problem, so for now, I just edited `lil_pass_forward_normal.hlsl` locally to avoid the bug:

```hlsl
//------------------------------------------------------------------------------------------------------------------------------
// AudioLink
BEFORE_AUDIOLINK
#if defined(LIL_FEATURE_AUDIOLINK)
    OVERRIDE_AUDIOLINK
#endif

// Process Main Color 2nd & 3rd after AudioLink
BEFORE_MAIN2ND
#if defined(LIL_FEATURE_MAIN2ND)
    float main2ndDissolveAlpha = 0.0;
    float4 color2nd = 1.0;
    OVERRIDE_MAIN2ND
#endif

BEFORE_MAIN3RD
#if defined(LIL_FEATURE_MAIN3RD)
    float main3rdDissolveAlpha = 0.0;
    float4 color3rd = 1.0;
    OVERRIDE_MAIN3RD
#endif

//------------------------------------------------------------------------------------------------------------------------------
```
My naïve solution may introduce other problems that I'm not aware of, but it seems to function properly in my current setup.
