### ISSUE TITLE
lilToonマテリアルを含むプロジェクトのビルド時にPlayerLoopの再帰呼び出しエラーが発生する

### ISSUE THREAD

**Issue by yuki-sorashiro** [lilxyzw/lilToon#197]
VRChatのワールドをビルドする際、lilToonマテリアルを含むプロジェクトでクリティカルなエラーが発生しています。
このエラーはAssetBundleのビルドプロセス中に起きております。

ただ、このエラーが発生してもビルドは成功し、アップロードも可能です。
ワールドの見た目や動作に問題は見られません。

**エラーメッセージ:**
```
An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it.
UnityEditor.BuildPipeline:BuildAssetBundles (string,UnityEditor.AssetBundleBuild[],UnityEditor.BuildAssetBundleOptions,UnityEditor.BuildTarget)
VRC.SDK3.Editor.Builder.VRCWorldAssetExporter:ExportCurrentSceneResource (bool,System.Action`1<string>,System.Action`1<object>)
VRC.SDK3.Editor.Builder.VRCWorldBuilder:ExportSceneResourceInternal (bool)
VRC.SDK3.Editor.Builder.VRCWorldBuilder:ExportSceneResource ()
VRC.SDK3.Editor.Builder.VRCWorldBuilder:ExportSceneResourceAndRun ()
VRC.SDK3.Editor.VRCSdkControlPanelWorldBuilder/<Build>d__114:MoveNext () (at ./Packages/com.vrchat.worlds/Editor/VRCSDK/SDK3/VRCSdkControlPanelWorldBuilder.cs:2153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()
```

**環境:**
- lilToonバージョン: 1.7.3
- Unityバージョン: 2022.3.22f1
- VRChat Creator Companion: 2.3.2
- VRChat SDKバージョン: 3.6.1
- プロジェクトテンプレート: Unity 2022 World Project
- OS: Windows11 23H2

**再現手順:**
1. Unity 2022 World Projectテンプレートを使用して新しいVRChatワールドプロジェクトを作成。
2. lilToonシェーダー（バージョン1.7.3）をプロジェクトにインポート。
3. lilToonシェーダーを使用して新しいマテリアルを作成。
4. シーンにオブジェクトを追加せずに、「Build & Test New Build」を実行。

**観察結果:**
- ビルドプロセス中にエラーが2回発生します。
- プロジェクト内にlilToonマテリアルのみを追加した状態でもエラーが発生します。
- プロジェクト内にlilToonマテリアルが存在しない場合、このエラーは発生しません。
- エラーが発生してもビルドは成功し、ワールドのアップロードも可能です。
- ビルドされたワールドの見た目や動作に問題は見られません。

**質問:**
このエラーは無視しても安全でしょうか？実際の動作に影響がないようですが、潜在的な問題がある可能性はありますか？

この問題についての洞察や支援をいただけると大変ありがたいです。

**Comment by lilxyzw** [comment]
こちらでも発生を確認しましたがビルドに影響はないようです。

**Comment by yuki-sorashiro** [comment]
ご確認くださりありがとうございました！

**Comment by muscat86** [comment]
私も同様、ビルド時に2つのエラーを吐き出します。
liltoon1.8.3でも同じでした。
いろいろ確かめたところ、unity2022.3.6f1で作成したworldだとエラーは発生しませんでした。
