### ISSUE TITLE
ノーマルマップのWrapModeが無視されて、MainTexのWrapModeが用いられる。

### ISSUE THREAD

**Issue by takecccc** [lilxyzw/lilToon#21]
ノーマルマップのサンプリングにMainTexのサンプラーが使われているため、ノーマルマップのWrapModeが無視されてしまいます。
ノーマルマップのサンプラーは別にできないでしょうか？

MainTexはRepeatによる境界が出ないようにClamp指定したく、ノーマルマップは布の質感を出すためにタイリングしてRepeatしたいということが実現できず困っています。

**Comment by lilxyzw** [comment]
通常のノーマルマップは立体感を付ける使い方、ノーマルマップ2ndの方はTilingして細かい質感付けを行う想定なので、次のバージョンで以下のような調整を加えてみます。
|テクスチャ|サンプラー|
|-|-|
|`_BumpMap`|`_MainTex`と共有（現状のまま）|
|`_Bump2ndMap`|`sampler_trilinear_repeat`（Repeat固定）|

以下のテクスチャは固有のサンプラーを持っているためテクスチャのインポート設定が利用されます。これら以外は基本的に`_MainTex`の設定が共有されますが、もしTilingを行いたい（行う機会が多い）ものがございましたらご連絡ください。
- `_MainTex`（メインカラー）
- `_Main2ndTex`（メインカラー2nd）
- `_Main3rdTex`（メインカラー3rd）
- `_EmissionMap`（発光テクスチャ）
- `_Emission2ndMap`（発光テクスチャ2nd）
- `_AudioLinkMask`（AudioLinkのマスク）
- `_OutlineTex`（輪郭線の色）

サンプラーの挙動に関して他の方からも同様のお問い合わせをいただいており、これらについてはマニュアルになかったため追記を行う予定です。

**Comment by takecccc** [comment]
ありがとうございます。対応として問題ないと思います。
他にもTilingを行う機会が多そうなものが無いか見てみましたが、特に見当たりませんでした。

**Comment by takecccc** [comment]
> 通常のノーマルマップは立体感を付ける使い方、ノーマルマップ2ndの方はTilingして細かい質感付けを行う想定

uv0は左右のuvを重ねてテクスチャサイズを節約する場合がありますが、その場合ノーマルマップ2ndにもuv0が適用され左右でuv分かれてしまうので、中央に切れ目が生じてしまいます。
ノーマルマップ2ndのサンプラーをrepeatに固定するのであれば、ノーマルマップ2ndもメインカラー2nd同様にUV Modeを選択できるようにすると利便性が向上します。

**Comment by lilxyzw** [comment]
ありがとうございます。Pull Requestをdevブランチの方にマージいたしました。ノーマルマップには不要だと思われるUVモード`Rim`については https://github.com/lilxyzw/lilToon/commit/d421ead6dfebad19cacfbb9f1344da610163dd8e にて私の方で削除しています。

**Comment by takecccc** [comment]
ありがとうございます。理解が足りず不要なモードを含めてしまいお手数おかけいたしました。
正常に動作することを確認いたしました。

**Comment by lilxyzw** [comment]
マニュアルへの記載が終わったのでこちらのIssueはCloseいたします。
