### ISSUE TITLE
Ver.18.1にてVRCワールドのアップロードに失敗する

### ISSUE THREAD

**Issue by East-vrc** [lilxyzw/lilToon#214]
本来アバター用シェーダーで制作されているシェーダーを
ワールドに使う事自体お門違いな気もしますが、
ワールドにアバターを使うワールドにて、アップロード時最新バージョンの18.1を使ってあげると
・An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it.
 ・Upload Was Canceled
・TaskCanceledException: A task was canceled.
という３つのエラーがビルド時にエラーが出てアップロードがキャンセルされます。
どうしても上がらなかったので、17.3のバージョンに落とした状態でプロジェクトに入れると問題なくアップロードされました。

**Comment by noritama-vrc** [comment]
こちらでも再現しまして、確認したところ #180 の対応に問題がありそうです。

その修正で
UnityEditor.SceneManagement.EditorSceneManager.OpenScene
を呼ぶよう修正してますが（2か所）、
これが VRChat の World Project での アップロード処理と衝突し、アップロードがキャンセルされている可能性があります。

OpenSceneの2か所をコメントアウトすると、正常にアプロードできます。

**Comment by myxyy** [comment]
https://github.com/lilxyzw/lilToon/pull/216
こちら修正PRを作成しました。
ご迷惑をおかけして申し訳ございません。

**Comment by lilxyzw** [comment]
ありがとうございます🙇
修正を取り込みました
