### ISSUE TITLE
ファーにおいて、陰影や(細い)リムライトによって謎の模様が浮かび上がる

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilToon#218]
Twitterで見かけたので試してみました。
Unity: 2022.3.22f1
lilToon 1.8.1

仕様であればclosed as not plannedしていただいて問題ありません。

- 陰影 0 リムライト(細さ 3)
![image](https://github.com/user-attachments/assets/6e2727ef-db0d-4692-9e7c-dae4aaa48c06)

- 陰影 1 リムライト(細さ 3)
![image](https://github.com/user-attachments/assets/64f8e582-c079-4b35-98b2-aef398861078)

- 陰影 0 リムライト(細さ 0.1)
![image](https://github.com/user-attachments/assets/04bb467e-bd2b-490f-9259-41bda6c6fcc5)

- 陰影 1 リムライト(細さ 0.1)
![image](https://github.com/user-attachments/assets/26ed9f00-1dfc-4fef-b12e-c3b57a4dbf27)

**Comment by lilxyzw** [comment]
こちら仕様となります。設定値の変更で目立たないように調整することを想定しています。
