### ISSUE TITLE
境界線設定のマスクと太さを0.999以上にするとスライダーの表示が消える

### ISSUE THREAD

**Issue by kesera2** [lilxyzw/lilToon#222]
# 概要
いつもお世話になっています。UIに関する軽微な不具合を見つけました。
簡易設定モードと詳細設定モードともに境界線設定のマスクと太さを1にするとスライダーが消えるようです。
0～0.999まではスライダーが存在し、それ以上になるとスライダーが消え入力欄のみになりました。
![image](https://github.com/user-attachments/assets/03c48b4d-4ef8-4afb-a425-3395debc6f9f)
![image](https://github.com/user-attachments/assets/3d223e1f-a683-42bb-9f35-067cea9cae95)
![image](https://github.com/user-attachments/assets/3520b37a-ddbf-4793-b82d-7bbe19a56239)
![image](https://github.com/user-attachments/assets/78a0f376-e0e5-47a3-a7b5-9fde4d2e38c5)

# 動作環境
・Windows11
・Unity 2022.3.22f1
・lilToon Version 1.8.3

**Comment by lilxyzw** [comment]
こちらは仕様です。Unityのスライダーは範囲以上の値を入力できませんが、アウトラインに大きな値を入力したいケースがあるため1以上にすると通常の数値入力に切り替わるようになっています。
