### ISSUE TITLE
Maskテクスチャのチャネルの扱いについて

### ISSUE THREAD

**Issue by takecccc** [lilxyzw/lilToon#23]
Maskとして用いられるテクスチャの扱いについて、確認です。

私が確認したところ、Mask用のテクスチャおよびその扱い方は現在下記の通りでした。
SingleChannelにして品質を高めるために、多くのMaskはrチャネルのみを用いているものと思います。

このうち、rチャネル以外も用いるMaskテクスチャについて
1. 特記に書いてある通りツールチップ表記と扱いが異なるものがいくつかあります。
2.  _MatCapBlendMaskについて、2ndはrのみを用いるのに、メインはrgbを別に用いています。他のカラー画像に対するMaskがrのみであることを考慮すると、ここはrのみを用いるはずのところを誤って実装しているのでしょうか？

また、マスクがrチャネルのみで良いことがツールチップによる表記以外に見当たりませんでした。
マニュアルに記載すると気づく方が増えるかと思います。

パラメーター | チャネル | 特記
-- | -- | --
_MainColorAdjustMask | r |  
_Main2ndBlendMask | r |  
_Main2ndDissolveMask | r |  
_Main2ndDissolveNoiseMask | r |  
_Main3rdBlendMask | r |  
_Main3rdDissolveMask | r |  
_Main3rdDissolveNoiseMask | r |  
_AlphaMask | r |  
_Bump2ndScaleMask | r |  
_AnisotropyScaleMask | r |  
_AnisotropyShiftNoiseMask | r |  
_ShadowStrengthMask | r |  
_ShadowBorderMask | rgb(1st,2nd,3rd) | ツールチップ表記がR
_ShadowBlurMask | rgb(1st,2nd,3rd) | ツールチップ表記がR
_MatCapBlendMask | rgb | 2ndはrのみ用いているのに、メインはrgb
_MatCap2ndBlendMask | r |  
_EmissionBlendMask | rgba | ツールチップ表記がR
_Emission2ndBlendMask | rgba | ツールチップ表記がR
_AudioLinkMask | rgb | ツールチップ表記なし（通常とspectrumで挙動変更）
_DissolveMask | r |  
_DissolveNoiseMask | r |  
_OutlineWidthMask | r |

**Comment by lilxyzw** [comment]
1acb48e にて修正しました。`_MatCap2ndBlendMask`については加算MatCapをハイライトとして使う場合に部分ごとに着色したい場合があるため通常のMatCapのマスクと同様にRGBチャンネルを使う方向で修正を加えました。マニュアルへの記載については後日行います。

**Comment by lilxyzw** [comment]
マニュアルへの記載、ツールチップ表記の修正が終わったのでこちらのIssueはCloseいたします。
