### ISSUE TITLE
lilToonのファーの描画がmacOSでは正しく行われない問題

### ISSUE THREAD

**Issue by smizuoch** [lilxyzw/lilToon#232]
バグ: lilToonのファーの描画がmacOSでは正しく行われなわれずプレビューができません。
再現方法: Windowsで作成されたファーを含むマテリアルをmacOS Unityにインポートするとマテリアルは Windows での動作と同じように動作しません。

# 可能であれば
Unityバージョン: 2022.3.22f1
lilToonバージョン: 1.8.3
macOSバージョン: 15.1.1（24B91）

またVRChatにアバターをアップロードした場合VRChat内での描画は正しく行えています。

**Comment by anatawa12** [comment]
これは Unity の Metal 対応が、 Geometry Shader に対応していないため仕様です。

**Comment by smizuoch** [comment]
ありがとうございます。

**Comment by smizuoch** [comment]
ありがとうごいざいます。
UnityのMetal対応において、Geometry Shaderがサポートされていない仕様について理解しました。
この点に関しては、現状の制限として認識し、クローズいたします。
