### ISSUE TITLE
formatted config json?

### ISSUE THREAD

**Issue by anatawa12** [lilxyzw/lilToon#25]
I think the ProjectSettings folder should be tracked via git.
However, `lilToonSetting.json` is unformatted JSON so the diff is not good to understand & merge.
Can you format lilToonSetting.json?

**Comment by lilxyzw** [comment]
Changed to format json in the development branch. The temporary json (in the `Temp` folder) hasn't changed. This change will be reflected in version 1.3.2.

**Comment by lilxyzw** [comment]
A fix for this problem has been applied in lilToon 1.3.2 and later releases.
