### ISSUE TITLE
UV設定 -> 角度で１を入力すると0.9999999になる

### ISSUE THREAD

**Issue by mzmt** [lilxyzw/lilToon#26]
### version
liltoon 13.1

### gif
![lil](https://user-images.githubusercontent.com/13535662/178134846-843cc547-076b-415f-8ba7-fbb03640827c.gif)

**Comment by lilxyzw** [comment]
弧度法→度数法の再計算時、floatの精度の問題で入力値とマテリアルに保存される値に誤差が発生していました。そのため、表示上の値を丸める処理を追加することでこの問題を回避しました。この修正はバージョン1.3.2にて反映されます。

**Comment by lilxyzw** [comment]
lilToon 1.3.2以降のリリースからこの修正が反映されています。
