### ISSUE TITLE
How to animate a specific material in multi-material object?

### ISSUE THREAD

**Issue by TizzureOne** [lilxyzw/lilToon#27]
For example, I'm trying to make a "eye" material hue shift animation, but when I do it, all material on this object use liltoon shader will apply the hue shift with this animation instead of only "eye" material, then my avatar get a weird colored face.
How to animate a specific material in multi-material object?

**Comment by lilxyzw** [comment]
Unity seems to animate per object (not per material slot).
[Animating multiple materials? - Unity Answers](https://answers.unity.com/questions/1132207/animating-multiple-materials.html)

If you want to animate only certain material slots, here are some possible methods
- Create as many shader variations as there are materials (not practical)
- Create an animation that does not manipulate the properties of the material, but replaces it with another material (material replacement can be done on a slot-by-slot basis)
- Separate only the material slots you want to animate to other objects
- Use a color correction mask (areas painted black with the mask will not be color corrected, so you can apply color correction only to specific materials by assigning a black texture to the materials you do not want to change)

**Comment by TizzureOne** [comment]
In my situation, seems method 3 was the only option. Thanks for helping!
