### ISSUE TITLE
Generated texture names are inconsistent when baking

### ISSUE THREAD

**Issue by hyblocker** [lilxyzw/lilToon#28]
When baking a texture using the Bake category in Optimization, all textures prepend the string `Baked_` to the generated texture's file name, with the exception of shadow textures. Shadow textures do not prepend `Baked_` to the file name when baked through this menu. Is this intentional behavior?

**Comment by lilxyzw** [comment]
The file names have been unified without "Baked_" because it makes the file names unnecessarily long. This change will be applied in version 1.3.2.
