### ISSUE TITLE
SetupShaderSettingFromMaterialでLIL_FEATURE_Main2ndDissolveMaskが設定されない模様

### ISSUE THREAD

**Issue by bdunderscore** [lilxyzw/lilToon#29]
![image](https://user-images.githubusercontent.com/64174065/180215801-5c6bce8f-d323-4047-9a2a-d5bea501d5c1.png)
![image](https://user-images.githubusercontent.com/64174065/180215833-131c594c-cc24-46f2-a503-8576983e75ab.png)

こちらの設定でMain2ndのDissolveを使用しても、LIL_FEATURE_Main2ndDissolveMaskが自動設定されないため動作しません。
SetupShaderSettingFromMaterialで適当にtrueに設定すると正しく動作します（正しい判定基準は調べきれてないのでPRできるほどは修正できてませんが）

**Comment by lilxyzw** [comment]
開発ブランチの方でこの問題の修正を行いました。この修正はバージョン1.3.3で反映される予定です。私の方で正しく動作するようになったことを確認しましたが、もし問題があれば改めて連絡いただけたら幸いです。

**Comment by lilxyzw** [comment]
lilToon 1.3.3以降で修正が反映されました。
