### ISSUE TITLE
ラメ機能のマスクテキスチャーがUVモードを無視してしまう

### ISSUE THREAD

**Issue by bdunderscore** [lilxyzw/lilToon#31]
ラメ機能を一部分だけで切るために、別UVチャンネルを用意して、2x1のマスクテキスチャーに充てるようにUVを調整してみたのですが、どうやらラメ機能のUVモード設定がラメの表示位置だけに影響して、マスクの方には影響しないようです。

高解像度のマスクテキスチャーを用意するのは避けたいので、できればマスクにも影響するUVモード設定がほしいです。

**Comment by lilxyzw** [comment]
ラメ機能のマスクにUVモード設定を追加しました。こちらは1.3.3で正式実装予定です。

**Comment by lilxyzw** [comment]
lilToon 1.3.3以降からラメ機能のマスクでUVモードが利用できるようになりました。テクスチャの横のFoldoutからUVに関する設定を開くことができます。
