### ISSUE TITLE
Liltoon's tessellation and fur shader doesn't work in macos 

### ISSUE THREAD

**Issue by hjliag** [lilxyzw/lilToon#32]
バグ: liltoon's tessellation shader materials and fur shader materials doesn't work in macos environment.
再現方法: When I import materials that are created in windows to my mac unity, the materials does not behave as it behaves in windows.

# 可能であれば
Unityバージョン: 2019.4.31f1
lilToonバージョン: 1.3.2

I can only see these warnings in unity console logs:
There are inconsistent line endings in the 'Assets/lilToon/Shader/ltspass_transparent.shader' script. Some are Mac OS X (UNIX) and some are Windows.
This might lead to incorrect line numbers in stacktraces and compiler errors. Many text editors can fix this using Convert Line Endings menu commands.

there are many warnings like this for other shader files too.

thank you

**Comment by lilxyzw** [comment]
In version 1.3.5, auto-generated shader line breaks have been changed to force the Windows format. Maybe this issue has been fixed.
