### ISSUE TITLE
Tilling & Offset Missing

### ISSUE THREAD

**Issue by bc15kle** [lilxyzw/lilToon#33]
Hello once again,

On the Universal Render Pipeline (URP), when I wanted to mess with the tilling & offset, I couldn't find a setting for them, however, the "Main Color 2nd" layer has the said tilling & offset settings.

![image](https://user-images.githubusercontent.com/42741373/181576857-cbd758d7-363b-4338-b6b7-ead3cd0584d5.png)

So, here I am asking if the tilling & offset for the "Main Color" are hidden somewhere else, or they will be added in the future? Thanks.

**Comment by lilxyzw** [comment]
You can find it here in the Advanced tab. The settings for textures that do not have individual UVs are grouped together, as calculating UVs for all textures has a significant performance impact.
![image](https://user-images.githubusercontent.com/74490257/181600508-57b911ca-f793-44e0-b612-a4060181e8d6.png)
