### ISSUE TITLE
Materials not affected by Point light

### ISSUE THREAD

**Issue by bc15kle** [lilxyzw/lilToon#36]
On URP, in the editor's play mode, the point light works like a charm, zero issues. 

However on the actual build, the materials that use lilToon aren't affected by the Point Light anymore (I did set the point light's priority to important and marked the "Use Lightmap" button from the shader settings too. I also messed with the monochrome light values and shadows being affect the ambient light values, but no luck). 

I back-end checked the point light with a default material (I used a cube) and on the build, it confirmed to me that the point light doesn't disappear, but the lilToon materials used in the scene are ignoring the said point light.

**Comment by lilxyzw** [comment]
Thank you for your bug report. The problem was caused by over-optimization removing necessary parts. This fix will be applied in the next release.
