### ISSUE TITLE
Cutout not working in VRChat

### ISSUE THREAD

**Issue by CrossKun** [lilxyzw/lilToon#37]
Good evening!
I switched from Liltoon 1.2.12 to 1.3.4 today.
Now, whenever I upload an Avatar to VRChat the "Cutout" Shader becomes Opaque again.
This only happens in the uploaded version.
When I test my avatar in VRChat, Cutout works.
It seems to be something about the optimization process that causes this issue. When I go to shader settings and activate "optimize in Test mode", the shader becomes opaque in Test Mode too.

Please look at the eyes in the editor and in VRChat:
![Unbenannt](https://user-images.githubusercontent.com/7695859/181863805-5492cc42-e43b-4f77-affe-12c95a5e5a3b.png)

What I tried: 
Uninstalled Liltoon -> reinstalled
Installed Liltoon on a different PC
Tried it with another Avatar
Reset Material

Thank you very much for your support!

**Comment by lilxyzw** [comment]
Thank you for your bug report. I have checked the following steps and the problem did not occur. I am continuing to investigate the issue and would appreciate any comments on how to reproduce the problem so I can get started on a fix as soon as possible.

1. Create a project for Avatar in VRChat Creator Companion (with `VRCSDK 3.1.3`)
2. Import `lilToon 1.3.4`
3. Create a `Cube` GameObject
4. Delete the `Box Collider`
5. Add `Animator` and `VRC Avatar Descriptor`
6. Create a new material
7. Set `Rendering Mode` to `Cutout`
8. Assign `Default-Particle` to main color texture
9. Enable `Optimize in test build`
10. Apply the created material to the cube
11. Save the scene
12. Run `Build & Test` from VRChat SDK control panel

**Comment by CrossKun** [comment]
Good evening! Thank you for your fast response! I looked into it and I might have found the issue.
In Blender, I tried it with a cube and a transparent texture on top of it -> Unity -> VRChat. Everything works great.

I looked into the Avatar and the Eye-Shining is the issue because the eye has 3 layers
EyeShining (Transparent) -> Eye (Transparent -> Eyeball (opaque).
(The whole model has only 1 Material)
It seems that when two transparent faces collide, the top of it becomes opaque.
In the following picture shows that a bit of the eye can be seen, but is overlapped by the EyeShining faces.
I hope this helps to find the issue. Thank you very much for looking into it.
![x](https://user-images.githubusercontent.com/7695859/181996973-7b00f391-8731-4d2e-a9d9-4b4f9489c20b.png)

**Comment by lilxyzw** [comment]
This version may fix the problem. It includes fixes for bugs in some OS languages. (When converting properties as numbers, different characters were used for the decimal point, causing the shaders to not function properly.)
https://www.dropbox.com/s/y4uu96ikjgpnkos/lilToon_2022_0907_0207.unitypackage?dl=0

**Comment by CrossKun** [comment]
Thank you very much for taking your time and fixing the problem!!
It worked perfectly.
I'm very happy with Liltoon and you are a great creator! 
I will close the Issue.
