### ISSUE TITLE
インポート後にundeclared identifier 'DEFAULT_LIGHT_LAYERS'

### ISSUE THREAD

**Issue by KanjiKurita** [lilxyzw/lilToon#38]
インポート後に`undeclared identifier 'DEFAULT_LIGHT_LAYERS'`のエラーメッセージが出ました。
試しにDEFAULT_LIGHT_LAYERSを0として定義してみたところ、エラーメッセージは表示されなくなりますが描画されないようです。

サポート範囲よりも新しいバージョンですが参考に報告させていただきます。

# 可能であれば
Unityバージョン: Unity2022.2.0b
lilToonバージョン: 1.3.4
コンソールログ: 
```
Shader error in 'Hidden/lilToonGem': undeclared identifier 'DEFAULT_LIGHT_LAYERS' at Assets/lilToon/Shader/Includes/lil_common_macro.hlsl(1543) (on d3d11)

Compiling Subshader: 0, Pass: FORWARD_PRE, Fragment program with <no keywords>
Platform defines: SHADER_API_MOBILE UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_NO_CUBEMAP_ARRAY UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_NO_SCREENSPACE_SHADOWS UNITY_PASS_SRPDEFAULTUNLIT UNITY_PBS_USE_BRDF2
Disabled keywords: DOTS_INSTANCING_ON INSTANCING_ON SHADER_API_GLES30 UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_ENABLE_DETAIL_NORMALMAP UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHTMAP_RGBM_ENCODING UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_FULL_STANDARD_SHADER UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_VIRTUAL_TEXTURING
```
スクリーンショット: DEFAULT_LIGHT_LAYERSを1で定義して、顔のマテリアルにlilToonを割り当てたスクショです。
![image](https://user-images.githubusercontent.com/47598683/181907947-b5b9453c-3fd9-45a0-806b-639305240f5b.png)

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。シェーダーのエラーに関しては修正を行いましたが、シェーダーにエラーがなくても描画されない場合がある問題についてはUnity側の不具合である可能性が高いです。詳細は以下のIssueへの返信の通りになります。
https://github.com/lilxyzw/lilToon/issues/47#issuecomment-1239369504

**Comment by lilxyzw** [comment]
タイトルの`DEFAULT_LIGHT_LAYERS`の件については修正済みなのでこちらのIssueはCloseします。マテリアルが描画されなくなる場合がある問題についてはHDRP・URPで同様に発生する問題なので #47 の方で引き続き対応を考えます。
