### ISSUE TITLE
Suggestion: Uv Animation for 2nd and 3rd layer

### ISSUE THREAD

**Issue by ghost** [lilxyzw/lilToon#40]
Hello once again,

Here I am again, but this time with a suggestion: what about adding to each texture layer an uv animation to create something like a hologram effect easily? Sorry for bothering if this is already added and possible.

**Comment by lilxyzw** [comment]
I think it is a good idea. I will look into the possibility of adding the feature after fixing the currently identified bugs.

**Comment by lilxyzw** [comment]
UV scrolling was added in version 1.3.7.
