### ISSUE TITLE
Point Light not getting the proper priority

### ISSUE THREAD

**Issue by ghost** [lilxyzw/lilToon#43]
On the URP version of the shader, if there's ambiental light, a directional light, then eventually a point light in the scene, liltoon completely ignores the point light even if the intensity of the said point light's set to over 20. Other lit surfaces/shaders react properly to the point light while lilToon completely ignores it thanks to the directional & ambiental light that take over way more than point light's intensity.

![image](https://user-images.githubusercontent.com/42741373/185589344-f53a0f49-7a2d-4f68-9101-e4c3b0e27c41.png)
On the left's the lilToon material on the right a normal lit surface.

**Comment by lilxyzw** [comment]
lilToon blends all the lights in a scene and calculates the final light direction, preventing multiple shadows from being applied to a single character and making it look bad. This comes from anime lighting.

Example:
```
Light Direction += Ambient Light Direction * Ambient Light Intensity;
Light Direction += Sun Light Direction * Sun Light Intensity;
Light Direction += 1st Light Direction * 1st Light Intensity;
Light Direction += 2nd Light Direction * 2nd Light Intensity;
Light Direction += 3rd Light Direction * 3rd Light Intensity;
...
Light Direction = normalize(Light Direction);
```

The degree of influence varies with the intensity of the light, so if other lights are extremely bright, the point light may appear to be ignored (it actually has a slight influence).
