### ISSUE TITLE
Outline becomes unlit in some dark maps 

### ISSUE THREAD

**Issue by ellydots** [lilxyzw/lilToon#44]
**Affected Versions: 1.3.2, 1.3.3, 1.3.4**

**Issue:** In certain dark VRChat maps outlines becomes unlit depending on the direction you are facing. 
![lil-outline-unlit](https://user-images.githubusercontent.com/111697156/185799441-8e53afde-5b62-4898-bfdc-8ceff16fa983.png)
Expected Behavior: 
![lil-outline-normal](https://user-images.githubusercontent.com/111697156/185799445-c7ec3171-20c5-4da4-a245-b3ffbb0b915c.png)

**How to reproduce:** Use version 1.3.4 of liltoon with outline. Load the VRChat map "Absence". Look at yourself (NOT IN MIRROR) and rotate camera.
![lil-outline-settings](https://user-images.githubusercontent.com/111697156/185799435-2c156617-2b45-430c-9348-b95e58a158d3.png)

**Note:** This does not happen on version 1.3.1

**Comment by lilxyzw** [comment]
Thanks for reporting the bug.
This bug has already been fixed in the development version and the fix will be applied in version 1.3.5.

**Comment by lilxyzw** [comment]
This bug has been fixed in version 1.3.5. Please update as necessary.
