### ISSUE TITLE
Refraction material broken in VR with 1.3.5

### ISSUE THREAD

**Issue by Ess-Ka** [lilxyzw/lilToon#46]
With 1.3.5 update, refraction material is broken for VR. It works in VRChat mirrors, but not if you can see yourself or if other players looks at you in VR (Desktop mode works). With 1.3.4 everything was fine.

![grafik](https://user-images.githubusercontent.com/84975839/188758665-f3a30a97-09e6-4fe8-b582-64ed3f111e8a.png)
Eye-Detail in Unity

![grafik](https://user-images.githubusercontent.com/84975839/188758501-57e3c182-f10d-47ac-bf2b-6723446eb8d4.png)
Settings of refraction part (Cornea of eye)

![20220907011347_1_vr](https://user-images.githubusercontent.com/84975839/188758515-010fb859-3f9f-4d27-8e28-375b4bcade72.jpg)
How it looks in VRChat (screen/mirror in background is ok)

**Comment by Ess-Ka** [comment]
I have tested the fix in VR. Everything looks fine now. Thank you for the super fast fix!

**Comment by lilxyzw** [comment]
Thanks for testing! This fix will be applied in version 1.3.6.
