### ISSUE TITLE
Support of GTAvaCrypt V2

### ISSUE THREAD

**Issue by Ess-Ka** [lilxyzw/lilToon#48]
Is it planned, to support GTAvaCrypt V2 encryption in near future (32 bits instead of 4 floats)?

**Comment by lilxyzw** [comment]
I would like to support it, but it may take a long time because it is necessary to create a function similar to Poiyomi Toon Shader's material lock.

**Comment by Ess-Ka** [comment]
I was able to successfully implement GTAvaCrypt V2.1 for other shaders (Sunao/UTS/XSToon). I have checked, if it can be done also with latest GTAvaCrypt V2.8. But by default and because of the new design, it breaks support for any other shader than Poiyomi. 

So, I understand, that it is currently impossible to adapt it for lilToon, whitout updating the code of GTAvaCrypt too.

**Comment by Ess-Ka** [comment]
I have opened an issue for GTAvaCrypt, to ask, if integration of other shaders can be allowed again:
https://github.com/rygo6/GTAvaCrypt/issues/13

**Comment by lilxyzw** [comment]
I added support for GTAvaCrypt V2 in the development branch and verified that it works fine. If the GTAvaCrypt code is updated, the implementation may be changed.

**Comment by Ess-Ka** [comment]
Wow - this was super fast! I have tried to test with an clean, empty project with lilToon dev branch and the latest version of GTAvaCrypt V2.8: I had to disable this lines in AvaCryptV2Root, to be able, to encrypt an avatar model with lilToon material:
![grafik](https://user-images.githubusercontent.com/84975839/189764839-0e670c06-0fe4-4fc6-b82b-464c5b4d4cb0.png)

After this changes, the model was encrypted and the GTModelDecode file (yellow) was created and contains the modelDecode method. I remarked another GTModelDecode in the includes folder, which comes from your branch (file is empty):
![grafik](https://user-images.githubusercontent.com/84975839/189765005-ff5835e3-1430-453f-99b5-0ec0b42dcaf9.png)

In the material, I can see the encryption section with bitkeys. But, manually changing them (in editor or in editor play mode) , does not affect the model. Also, when setting an bitkey animator parameter, the bitkey will be updateded here, but nothing happens with the mesh.

So, it doesn't work for me. Have I forgot something?

**Comment by lilxyzw** [comment]
The GTAvaCrypt feature is only enabled when building an avatar. This is to avoid that lilToon does not have a material lock function and decoding is applied to all materials in the project. Currently, you can use GTAvaCrypt by following the steps below.

1. Encrypt your avatar by following the steps in GTAvaCrypt
2. Copy the generated GTModelDecode.cginc to `lilToon/Shader/Includes`
3. Upload your avatar (or enable `Optimize in test build` in lilToon settings and do `Build & Test`)

**Comment by Ess-Ka** [comment]
Thank you. Add the define to lil_common.hlsl helped. I can decrypt my avatar in editor, using the animator, but I will get this two error messages:
![grafik](https://user-images.githubusercontent.com/84975839/189863620-bace51cf-a0e8-44db-8d58-412e251defac.png)

When I upload the avatar, it stays still encrypted:
![grafik](https://user-images.githubusercontent.com/84975839/189864425-80698dcf-7046-43e6-aab1-a025681bd334.png)

**Comment by Ess-Ka** [comment]
I tried this to steps and with this, it works also in uploaded version:

lil_common_appdata.hlsl:
![grafik](https://user-images.githubusercontent.com/84975839/189869897-490bc411-50e4-437b-8069-017cc5e832e9.png)

lil_pass_forward_fakeshadow.hlsl
![grafik](https://user-images.githubusercontent.com/84975839/189869667-b672fde8-de12-4b99-9b10-f95b318974a2.png)

But probably, this is not 100% right... :-)

**Comment by lilxyzw** [comment]
Thanks, the error has been fixed with this commit.
https://github.com/lilxyzw/lilToon/commit/7546f941d6ce42d6fbc4bb5d59f2825e107c6091

**Comment by Ess-Ka** [comment]
Perfect - everything works fine, now! 👍 

If possible, it would be nice to have an additional shader setting checkbox, which activates the decryption in editor automatically as you mentioned:
#define LIL_FEATURE_ENCRYPTION to lil_common.hlsl.

But this has no priority. Thanks for implementing the new decryption feature in this short period of time :-)
