### ISSUE TITLE
Invisible setting on default in playmode

### ISSUE THREAD

**Issue by Yatzii93** [lilxyzw/lilToon#5]
Wondering if this is a bug or possible, I'd love to be able to have the shader off by default and then toggled on ingame but it seems by default even if it's turned off via the Base Setting in unity, the shader will auto turn on in playmode. The way around this I guess would be to turn it off via an animation but ideally I'd prefer it to be off by default. Any reponce would be amazing.

**Comment by lilxyzw** [comment]
Thanks for letting me know.  
There are two possible causes for this problem.
1. The object has an `Animator`. And the animation that sets `_Invisible` to 0 is played in it.
2. Some scripts will set `_Invisible` to 0.

Confusingly, a material becomes visible when `_Invisible` is 0, and invisible when it is 1.  
Create an object in the new scene that does not have a script, and if the problem still occurs, it may be a bug.  
It would be great if you could tell me the details of the Unity version and the object.
