### ISSUE TITLE
Fur (Cutout) + AO

### ISSUE THREAD

**Issue by Ess-Ka** [lilxyzw/lilToon#52]
I've remarked two problems, when using Fur (Cutout) with the AO setting. In my setup I use it on head and partially on body with an alpha mask (neck).

First problem:
When a AO value > 0 is applied, black artifacts becomes visible, depending of distance of camera. In VR, the number of black pixels is a lot higher (depends probably on FOV).

Example near (Desktop):
![grafik](https://user-images.githubusercontent.com/84975839/190135210-09000be2-3a48-4344-818b-d5f04760f572.png)

Example far (Desktop):
![grafik](https://user-images.githubusercontent.com/84975839/190135276-9b5a9c09-a327-46ad-b66c-55470c54efe5.png)
(in VR, the head would be completely black for this distance)

Second problem:
When Fur is only applied partially with an alpha map, AO is also applied on transparent parts. Is it possible, to add on option, which allows AO to respect the alpha map?
![grafik](https://user-images.githubusercontent.com/84975839/190134933-bf35df21-d9f0-4311-818b-e6eed2ff640d.png)

With opaque shader, the result looks like this:
![grafik](https://user-images.githubusercontent.com/84975839/190134225-819730b6-0a3c-41eb-b51b-69e70c12ea53.png)

With fur shader, the transparent parts looks too dark (to better show the effect, I have increased the AO value):
![grafik](https://user-images.githubusercontent.com/84975839/190134576-0835f3da-1fe7-4a87-a63b-786cce6ec9f9.png)

**Comment by lilxyzw** [comment]
These bugs have been fixed.

# Black artifacts
This problem was caused by MSAA. Fixed this by weakening the effect of AO when fur is rendered small.

# AO is applied ignoring the alpha mask
This is my mistake. Fixed this by weakening the AO based on the alpha mask.
