### ISSUE TITLE
Feature Request: Rim Light in Light

### ISSUE THREAD

**Issue by CrossKun** [lilxyzw/lilToon#53]
Currently, I would like to switch from Poiyomi 7 to LilToon.
Unfortunatly, a very important feature is missing for me.
The Rim Light is only showing in dark places, but I need it to be seen even when light is shining on it as well.
Maybe there is a way, but I couldnt find it.
I could make it work to have a white color surrounding it, but I need it to be a darker color to give it some kind of "always shadow around the body" feeling to it. (see attached picture)
The Color Code I used is #FF9898
I leave a picture of LilToon (up) and Poiyomi (Down) as a comparison

Something like an option to "multiply" the rim color is an idea I had.
If this is a feature you don't consider important, I understand it completly and you can close the issue!

Sincerly,
Crossaint

![rimlightnotshowing](https://user-images.githubusercontent.com/7695859/191365451-53984733-378d-414c-8692-8e05b7a0a3ee.png)

**Comment by lilxyzw** [comment]
Thanks for the feature request. A `Blending Mode` property has been added to rim light in version 1.3.7.

**Comment by CrossKun** [comment]
Thank you very much lil! It's perfect timing since I'm working on a new Avatar! I will try out the new feature for this Avatar! I'll close this topic.
I really appreciate your work!
