### ISSUE TITLE
Can't work in 2021.3.15f1 URP

### ISSUE THREAD

**Issue by AkilarLiao** [lilxyzw/lilToon#58]
just like title, thanks.

**Comment by lilxyzw** [comment]
It seems to be a Unity bug. According to this bug report shaders render correctly using version 2021.3.8f1.
https://issuetracker.unity3d.com/issues/sphere-gameobject-doesnt-get-rendered-when-using-unlit-dot-unlit-usepass-shader

**Comment by zgock999** [comment]
if it means no render after buid, disabling the "Strip unused variants" in global URP option fixes it.
It runs well on 2021.2.16f with disabling this.

横から失礼します。URPのproject settingsで「Strip unused variants」がONになってるとビルド後に表示できなくなるという仕様？（Quibliなんかもそうなるので仕様になるのかなあ）があるのでそれかも。
2021.3.16f1でその問題にぶつかってこのオプションで直ったので

RADME.mdあたりにURPで使う時の注意点として一筆あるといいかもですね

**Comment by yahagi-day** [comment]
このバグは 2021.3.19f1, 2022.2.7f1で修正されました
https://issuetracker.unity3d.com/issues/sphere-gameobject-doesnt-get-rendered-when-using-unlit-dot-unlit-usepass-shader

**Comment by lilxyzw** [comment]
This Issue is closed as this bug was fixed in 2021.3.19f1.

@yahagi-day ご報告ありがとうございます！
