### ISSUE TITLE
URP環境にてEditorとBuild後でライト反映の結果が異なる

### ISSUE THREAD

**Issue by clocknote** [lilxyzw/lilToon#59]
# URP環境にてEditorとBuild後でライト反映の結果が異なる

## 動作環境

- Windows 11
  - GeForce RTX 3080
- Unity 2021.3.16 (LTS), Unity 2022.2.1
  - Universal RP
  - lilToon 1.3.6

## 不具合の内容

URP環境にて、Editorとビルド後のライト反映の見た目に差が生じています。

検証の結果、lilToon上の設定で「影」にチェックボックスが入っていないマテリアルは、ビルド後にPoint Light, Spot Lightの影響を受けないようになっているようです。

## 再現手順

- Universal RPのプロジェクトを作成
- lilToon 1.3.6をインストール
- 適当なメッシュを生成、それぞれ下記の設定を行う
  - lilToonMultiで影にチェックボックスが入っていないマテリアルを適用
  - lilToonMultiで影にチェックボックスが入っているマテリアルを適用
- Point Light, Spot Lightなどを設置
- シーンをBuildして、Editor上の結果と比較する

### Editor
![editor](https://user-images.githubusercontent.com/5446018/210272153-25a355a0-5eca-48a2-8cc9-a245a9a1c113.png)

### Build
![build](https://user-images.githubusercontent.com/5446018/210272170-eeae444d-229e-4a07-9a88-4f421cc91a4d.png)

### Scene View
![scene](https://user-images.githubusercontent.com/5446018/210272178-4b749e8c-a43b-49ff-9f45-4f9db13f0b7f.png)

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。以下の手順で検証を行ってみました。

1. Unity Hubで`Unity 2022.2.1f1`、`3D (URP)`テンプレートで`E:\UnityProject\2022.2 URP`ディレクトリに新規プロジェクトを作成
2. 新規マテリアルを作成しシェーダーを`_lil/lilToonMulti`に変更
3. マテリアルを複製し、複製したマテリアルの`影設定`から`影`のチェックボックスをオンに
4. 新規に`Standard (URP)`でシーンを作成し、Sphereを2つ作成
5. `Sphere`は座標X=-0.8、`Sphere (1)`はX=0.8に配置
6. `Sphere`に最初に作成したマテリアルを、`Sphere (1)`に複製し影を有効化したマテリアルを適用
7. 検証用にDirectional Lightをオフにする
8. Point Lightを追加しY=1.25に配置
9. シーンを保存し`E:\UnityProject\2022.2 URP\Build`ディレクトリにビルド

結果としては両方のSphereにポイントライトが反映されており、こちらで不具合は確認できませんでした。`Project Settings/Graphics`にて`Shader Stripping`の設定を変更したら正常にビルドされたという報告もあるため、何らかの理由でビルドが正常に行われない場合があるかもしれません。こちらでも現象が確認でき次第改めて調査を行います。

**Comment by clocknote** [comment]
検証いただきありがとうございました。
再現しなかったとのこと、なるほどです。
こちらでももう少し掘り下げてみます。

**Comment by clocknote** [comment]
本件、現在も解決策が見つかっておらず、Unity、lilToon共に最新版を使用して再検証しました。
今回は配布可能なプロジェクトデータも作成しましたので、あわせてお送りいたします。

## プロジェクトデータ
https://www.dropbox.com/t/omK5vPo6QPYB6arX

## 動作環境
- Windows 11
  - GeForce RTX 3080
- Unity 2021.3.23 (LTS)
  - Universal RP
  - lilToon 1.3.7

## Editor
![editor](https://user-images.githubusercontent.com/5446018/232326779-673157b1-0360-4d54-b918-d9c215b56161.png)

## Build
![builds](https://user-images.githubusercontent.com/5446018/232326819-33d5b11c-ae7b-4726-9c70-ff3eceaad799.png)

**Comment by lilxyzw** [comment]
ありがとうございます、こちらでも現象が再現いたしました。シェーダーバリアント削減機能がURPのものと競合していたことが判明したため、URPでは削減機能を使用しないことで問題を回避するように変更を加えました。この修正は次回リリースで反映される予定ですが、Project Settingsから画像の箇所をオフにすることでも回避できます。お手数をおかけしました。

![strip](https://user-images.githubusercontent.com/74490257/232354899-f0fd42ec-83ed-46be-8f5a-c24999442650.png)

**Comment by clocknote** [comment]
ありがとうございます。
なるほど、自分も勉強になりました。ご丁寧にありがとうございました。
