### ISSUE TITLE
輪郭線の太さが0に近い時、両面描画有効でも裏面より輪郭線が上にレンダリングされる

### ISSUE THREAD

**Issue by thakyuu** [lilxyzw/lilToon#6]
# 輪郭線の太さが0に近い時、両面描画有効でも裏面より輪郭線が上にレンダリングされる

下記環境において、表題の状況を確認しましたので報告いたします。
お手数ですが想定した挙動であるかご確認お願いいたします。

※参考としてarktoonシェーダーの同設定時との比較イメージを添付しております

## 概要

* 片面メッシュに対して輪郭線の設定をし、太さを0などにした場合、両面描画有効な場合でも裏面側に輪郭線が優先してレンダリングされてしまう
* 太さは0や0.00001など、非常に小さい値の時に発生

## 想定される問題

* 輪郭線をマスクなどで制御する際、裏面の無い箇所で意図しない表現になる可能性がある

## 再現手順

1. UnityプリミティブのQuadをシーンに配置
2. QuadにLiltoonを適用したマテリアルを割り当て
3. Cull ModeをOffに設定
4. 輪郭線を有効化し、太さを0に設定
5. 輪郭線に設定された色が裏面側全体に表示されていることを確認

## 環境

* Windows 10 Pro 20H2
* Unity 2019.4.29f1 / Built-in Rendering Pipeline
* lilTtoon_1.1.5
  * arktoon-shaders-1.0.2.6(比較用)

## 参考イメージ

* UnityプリミティブのQuadに対し、liltoon/arktoonそれぞれでOutlineのWidthを0、Cull Back/Offの設定を行ったマテリアルを適用
* 上段は表面側、下段はY軸180度反転した裏面側を表示

![image](https://user-images.githubusercontent.com/4232108/129304586-d662324f-4ceb-4fd4-a0b5-bb0a8eec7e1e.png)

**Comment by lilxyzw** [comment]
ご報告ありがとうございます。こちらでも現象を確認いたしました。
lilToon 1.1.6で修正を反映いたしますが、シェーダープロパティのデフォルト値の変更のみで完結するため現在のバージョンでもレンダリング設定を変更することで改善されます。
1. 詳細設定内の`レンダリング設定`を開く
2. 輪郭線の`ZTest`をLessEqualからLessに変更
![image](https://user-images.githubusercontent.com/74490257/129318857-3f8211d2-3ebf-4996-8ac4-98bf4634cabc.png)

## 修正内容
- 裏面の描画を輪郭線の描画より優先させる
## 変更点
- 各シェーダーのProperties内の`_OutlineZTest`の初期値を4から2に変更
