### ISSUE TITLE
Unity 2022.2 URP Forward+ 環境で動作しない

### ISSUE THREAD

**Issue by clocknote** [lilxyzw/lilToon#60]
# Unity 2022.2 URP Forward+ 環境で動作しない

## 動作環境

- Windows 11
  - GeForce RTX 3080
- Unity 2022.2.1
  - Universal RP
  - lilToon 1.3.6
  - Forward+

## 不具合の内容

Unity 2022.2 TechStream URP環境にて、Forward+を使用すると、シェーダーエラーになります。

## 再現手順

- Unity 2022.2.1 Universal RPのプロジェクトを作成
- lilToon 1.3.6をインストール
- lilToonが適用されたメッシュを配置
- Rendering PathをForward+にする

### Forward
![FjheHyDaUAESEFn](https://user-images.githubusercontent.com/5446018/210273449-fa0e138e-80a7-4af7-9102-97acce29472c.jpg)

### Forward+
![Fjhcx1qakAIx42_](https://user-images.githubusercontent.com/5446018/210273456-b61362b7-2437-442a-8d0b-abdd67ef2e31.jpg)

**Comment by lilxyzw** [comment]
ご報告ありがとうございます。こちらのコミット（ https://github.com/lilxyzw/lilToon/commit/97a3ec2cb81c18249162afd124c1e27d1134c567 ）で修正を行ったので次回アップデート以降正常に動作するようになるかと思います。正式リリース前ですが、UPMから`https://github.com/lilxyzw/lilToon.git?path=Assets/lilToon#dev`をインポートすることで開発版をご利用いただくこともできます。

**Comment by clocknote** [comment]
お返事ありがとうございます。ちょうど入れ違いになってしまったようで失礼しました。
devブランチの方試させていただきましたが、無事こちらの環境でも正常に動作することが確認できました。
ご対応ありがとうございました。
