### ISSUE TITLE
Feature Request: Emission Mask の乗算

### ISSUE THREAD

**Issue by kobi32768** [lilxyzw/lilToon#61]
現在 lilToon の Emission Mask は加算のみ対応かと思われますが乗算を前提とした Emission Mask も多く存在するため乗算による Emission が欲しいです。
また、メインテクスチャへの依存度を下げられるためユーザの保守性の面からも有用です。
https://lilxyzw.github.io/lilToon/#/ja-jp/color/emission

**Comment by lilxyzw** [comment]
機能リクエストありがとうございます。バージョン1.3.7にてEmissionに`合成モード`プロパティを追加しました。通常・加算・スクリーン・乗算から任意の合成方法を選択できます。
