### ISSUE TITLE
Feature Request: PBR Packing

### ISSUE THREAD

**Issue by 4liceD** [lilxyzw/lilToon#62]
It would be really cool for vram optimisation to support packing of pbr textures.
Preferably in arm order so you don't have to import the alpha channel of that texture for further optimisation.
Basically means Roughness/Smoothness, Metallic and Ambient Occlusion put into a single texture and you assign each map to a different color channel.
For example:
Ambient Occlusion in Red
Roughness/Smoothness in Green
Metallic in Blue

**Comment by lilxyzw** [comment]
I'm thinking of making use of the color channel as below. This is common for Standard Shader, URP Lit, and HDRP Lit.
|Texture Channel|Parameter|
|-|-|
|Red|Metallic|
|Green|Occlusion|
|Blue|None|
|Alpha|Smoothness|

**Comment by 4liceD** [comment]
MOES is still better than unpacked, but under normal compression MSA/MRA takes half the amount of vram compared to MOES because you don't need to import the alpha channel. So it might be worth to look into different packing orders, or for more advanced users give the option to select the channel yourself.
<html>
<body>


Texture Channel | Parameter
-- | --
Red | Metallic
Green | Smoothness
Blue | Occlusion


</body>
</html>

**Comment by 4liceD** [comment]
Managed to do it myself, trying to maintain it if you decide to go MOES instead.
https://github.com/4liceD/lilToon-MSA-Packing
