### ISSUE TITLE
Liltoon Unlit Bug 

### ISSUE THREAD

**Issue by megu84844** [lilxyzw/lilToon#64]
![da477987b1574426d31e7965fd060379](https://user-images.githubusercontent.com/104563520/215753996-b3c7d9a9-acc4-481c-8680-cf71629dc83d.png)
bug in all version
I tried to reinstall unity and does not work.
I was using this for avatar brightness
the lightning works in unity but It does not work in vrchat
the animation breaks.

**Comment by megu84844** [comment]
I tried to click fix now but it goes back to zero.

**Comment by megu84844** [comment]
![b86bbc3d0323601b4801d0fab2cb535e](https://user-images.githubusercontent.com/104563520/215755200-c83f6774-3027-457f-9108-bafc2e7a107c.png)

**Comment by megu84844** [comment]
it only works in unity

**Comment by megu84844** [comment]
![7bbcf4e246078e42eb572f54693418ac](https://user-images.githubusercontent.com/104563520/215755644-b04319bb-c557-4d30-948b-d37e2d65e346.png)
here are my settings

**Comment by lilxyzw** [comment]
`Fix Now` button fixes the property value, not animations.

First, you need to isolate the cause of the problem. Add BlendShapes to that animation and see if the animation plays in VRChat. If it doesn't play, it's most likely a problem with the Animator, ExpressionParameters, or ExpressionsMenu.
