### ISSUE TITLE
「lilToonMultiに変換」ボタンが動作しない

### ISSUE THREAD

**Issue by clocknote** [lilxyzw/lilToon#66]
# 「lilToonMultiに変換」ボタンが動作しない

## 動作環境

- Windows 11
  - GeForce RTX 3080
- Unity 2021.3.5f1 (LTS), Unity 2022.2.5f1
  - Built-in RP, Universal RP
  - lilToon 1.3.7

## 不具合の内容

`lilToon` シェーダーを選択しているマテリアルのInspectorから、最適化項目の `lilToonMultiに変換` ボタンを押した際、ボタンのラベルに書かれた内容の期待した動作が行われませんでした。

## 再現手順

- Universal RPのプロジェクトを作成
- lilToon 1.3.7をインストール
- `lilToon` シェーダーを適用したマテリアルを作成
- `lilToonMultiに変換` ボタンを押す

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。シェーダーを置き換える操作がされていなかったことが原因でした。修正を加えたので次回バージョンにて反映いたします。
