### ISSUE TITLE
VPMリポジトリを生成してください

### ISSUE THREAD

**Issue by bdunderscore** [lilxyzw/lilToon#69]
VRChatのVCCから導入できるように、VPMリポジトリを生成してください。今は少し不便（初期登録にはCLIが要るなど）でも現在のUPM、unitypackageのどちらかのワークフローよりは利便性が上がるのではないかと思います。また、今後前提として扱えるようになる見込みです。

すでにパッケージのzipを生成しているようなので、あとはリリース時にリポジトリを更新するだけが残っている状態です。（もしかしてどっか裏で生成してるのでしょうか？）

modular-avatar も出してるので、よろしければワークフローのサンプルとしてご参考ください。
* https://github.com/bdunderscore/modular-avatar/blob/main/.github/workflows/trigger-repo-rebuild.yml
* https://github.com/bdunderscore/vpm-repo/blob/main/.github/workflows/publish.yml
* https://modular-avatar.nadena.dev/ja/docs/faq#vcc%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6modular-avatar%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%81%8B (現在の利用方法)

**Comment by lilxyzw** [comment]
VPMリポジトリの方作成しました。VCCから追加できるようになったら推奨のインストール方法としてドキュメントにも説明を追加する予定です。
https://github.com/lilxyzw/vpm-repos

**Comment by lilxyzw** [comment]
VCC 2.1.0でGUI上でリポジトリの追加が可能になったのでドキュメントにも説明を追加しました。
