### ISSUE TITLE
Unable to adjust decal alpha with MSDF texture when alpha is specified in 'main color/alpha'

### ISSUE THREAD

**Issue by HotKonti** [lilxyzw/lilToon#74]
### Issue
I'm attempting to improve the quality of a texture by using an MSDF texture in 'main color 2nd' while lowering the resolution of the existing texture. However, if an alpha has already been specified in 'main color/alpha', I can't adjust the alpha of that part when using a decal with the MSDF texture, so I can't achieve the desired effect.

### Solution
To be able to adjust the alpha of a decal when using an MSDF texture, I need to modify the code. For example, when applying the decal, I can ignore the alpha value specified in 'main color/alpha' and instead use the alpha value specified in the MSDF texture. This way, I can achieve the desired effect when using the decal.

**Comment by lilxyzw** [comment]
I added a function to overwrite with the transparency of the main color 2nd and 3rd. This is available in the next version.
