### ISSUE TITLE
Custom liltoon shader not being applied in VRChat

### ISSUE THREAD

**Issue by HotKonti** [lilxyzw/lilToon#75]
I created a custom shader based on the Liltoon shader, and when I test it in Unity, it works fine. However, when I upload it to VRChat, the default Liltoon shader is applied instead of my custom one.

Using the liltoonMulti shader instead of Liltoon solves the issue, but it doesn't feel like a proper solution. Can you guide me on how to resolve this issue?

**Comment by Forenard** [comment]
同じ症状が出ています。
ドキュメントにある作例(lilToonGeometryFX)を改変したシェーダーが動かず、元々のlilToonGeometryFXも動きませんでした。
(デフォルトのliltoonになります)

**Comment by lilxyzw** [comment]
@Forenard こちらの環境で確認しましたが、デフォルトのlilToonではなくUnlitシェーダーにフォールバックされるようでした。最適化時にエラーになることが原因でしたので、lilToon本体と[lilToonGeometryFX](https://github.com/lilxyzw/lilToon/blob/Document-dev/files/lilToonGeometryFX_1.0.1.unitypackage)両方に修正を加えました。

@HotKonti If it falls back to the Unlit shader, it's probably a build-time error. There may be shader errors in the console log.
