### ISSUE TITLE
メインカラー2nd,3rdでテクスチャを指定せずにデカール化するとVRChatにアップロードしたアバターのみ描画が異なる

### ISSUE THREAD

**Issue by kurotu** [lilxyzw/lilToon#76]
## 不具合の内容
メインカラー2nd,3rdでテクスチャを指定せずにデカール化するとVRChatにアップロードしたアバターのみ描画が異なります。
VRCSDKの `Build & Test` ボタンによるローカルビルドでは問題なく、Unityと同じ描画になります。

Unityでの表示
![image](https://user-images.githubusercontent.com/74851548/225364520-251a782d-bfc0-4411-b6fa-dd247a065ca6.png)

VRChatでの表示
![image](https://user-images.githubusercontent.com/74851548/225365076-9e1e0cb3-0b28-4cd1-9cfc-ab6448bbe1fe.png)

## 再現手順
1. 新規プロジェクトを作成
2. lilToonを使用するマテリアルを作成し、以下のように設定
    - メインカラー
        - テクスチャを割り当て
    - メインカラー2ndまたは3rd: ON
        - 色のみを変更し、テクスチャを割り当てない
        - デカール化: ON
        - X座標: 0.5
        - Y座標: 0.5
        - X軸サイズ: 0.5
        - Y軸サイズ: 0.5
3. 2.のマテリアルを使用したアバターをVRChatにアップロード

## 発生環境
- lilToon: 1.3.7
- Windows 10 21H2
  - GeForce RTX 2060 Super
- Unity 2019.4.31f1
  - VRCSDK 3.1.11

**Comment by lilxyzw** [comment]
ご報告ありがとうございます。テクスチャ未使用の場合に最適化時にデカール化の処理が除去されてしまうことが原因でした。こちらの修正は次のバージョンで反映予定です。
