### ISSUE TITLE
Dither feature

### ISSUE THREAD

**Issue by bc15bekl** [lilxyzw/lilToon#79]
Hello, lilToon doesn't seem to have a fancy fade to transparency effect for when the camera gets too close to a model, one way it could be implemented is via a dither system similar to the Mario games. If this thing already exists, what settings are used for it with the dither in mind?

**Comment by lilxyzw** [comment]
I added dither to cutout shader. Also, transparency change with distance can be used with distance fade. This is available in the next version.

**Comment by bc15bekl** [comment]
> I added dither to cutout shader. Also, transparency change with distance can be used with distance fade. This is available in the next version.

It works as intended, but there's a problem. Preset save doesn't work on it.
