### ISSUE TITLE
Attempting to use lilToon on Unity 2021.3.5f1 (SLZURP). and heres the result

### ISSUE THREAD

**Issue by Rinae1x** [lilxyzw/lilToon#81]
![issue#1](https://user-images.githubusercontent.com/114847394/228746346-e54c2a7e-35da-4035-a3f2-cd5d32aafc1d.png)

**Comment by Rinae1x** [comment]
After i tried to re-install, then theres still an issue occurred by no reason, and i completely have no idea how did that happened.
![issue#2](https://user-images.githubusercontent.com/114847394/228748569-70c03b1d-7033-421b-8b24-f8e2e3703ba0.png)

**Comment by lilxyzw** [comment]
SLZURP version was not parsing correctly because the version notation changed. The process has changed to get the version from the Core RP instead.
