### ISSUE TITLE
VRCLens導入済みアバターでFix LightingするとBoundsが非常に大きくなる

### ISSUE THREAD

**Issue by Assault1892** [lilxyzw/lilToon#83]
VRCLens側の問題の気もしますが一応...

## 不具合の内容
VRCLens 1.8.1 を導入したアバターに対して lilToon > Fix lighting すると、Boundsの値が非常に大きな値に設定されます。
また、アバターの大きさによってはVRChat側の (実質的な) 制限に引っかかるレベルで大きく設定されることがあります。
![Hakka scale 1.365](https://user-images.githubusercontent.com/34514603/233635143-a9304ffd-619d-42d6-befe-64297942c1f6.jpg)
![VRCSDK Performance Rank](https://user-images.githubusercontent.com/34514603/233635150-1b2640bc-8b0c-4722-a435-ef7db4433420.png)

## 検証方法 (再現手順)
1. 新規でプロジェクトを作成し、HierarchyにVRCLensと各アバターのPrefabを配置
2. アバターのPrefabをそれぞれ複製し、片方にVRCLensを適用、もう片方は未適用の状態で lilToon > Fix Lighting
3. 服のメッシュのBoundsを比較する

## スクリーンショット

<details>

### 薄荷
![Hakka Comparison](https://user-images.githubusercontent.com/34514603/233633853-2aa5cf4a-079e-496b-80a2-1cfa0fff1676.png)

### ホノカ
![Honoka Comparison](https://user-images.githubusercontent.com/34514603/233633260-ba51f8eb-3c1a-46a0-95bc-3d5df29bd821.png)

### カリン
![Karin Comparison](https://user-images.githubusercontent.com/34514603/233631926-932d054c-365d-47fc-b9c9-3cdf7f4128b2.png)

</details>

## 環境
- Windows 10 22H2
  - Unity 2019.4.31f1
- VRCSDK3 (Base, Avatar) : 3.1.13
- lilToon : 1.3.7
- VRCLens : 1.8.1
- テストに使用したアバター
  - 薄荷 1.4.4
  - ホノカ 1.1.0
  - カリン 1.11

**Comment by lilxyzw** [comment]
ご報告ありがとうございます。Boundsの計算方法に変更を加えて極端に大きくなりにくくしました。ただし全てのメッシュをカバーできるようにBoundsを統一するという仕様上、1つでも遠い座標にメッシュがある場合はどうしても大きくなります。こちらの修正は次のバージョンで反映予定です。

**Comment by Assault1892** [comment]
ありがとうございます！ :tada:
