### ISSUE TITLE
vpm/upmでインストールしている場合にバージョンにかかわらずunitypackageのimportを拒否する

### ISSUE THREAD

**Issue by anatawa12** [lilxyzw/lilToon#84]
vpm/upmでインストールしている環境でAssetsに展開するunitypackageをimportするとパッケージが壊れることがあるため古いバージョンをimportするのと同様に拒否するといいと思います。

**Comment by lilxyzw** [comment]
ありがとうございます。lilToonがvpm/upm経由でインストールされている場合にも警告を出すように変更を加えました。
