### ISSUE TITLE
MToon変換: HDRカラーのMain ColorがMToonのColorにHDRの状態で渡される

### ISSUE THREAD

**Issue by 0b5vr** [lilxyzw/lilToon#85]
こんにちは。いつもlilToonの素敵なお仕事をありがとうございます。

lilToonでは、Main ColorにHDR Colorを設定することができますが、
ここに1以上の値を入れた状態で「Convert to MToon (VRM)」ボタンを用いてマテリアルをMToonに変換したところ、
MToonのLit Color上でもHDR Colorとなってしまっているようです。
MToonのLit ColorはHDR Colorを許容しないため、[0, 1]の範囲内にキャストして変換していただきたいです。

コードとしてはこのあたりになりますでしょうか？

https://github.com/lilxyzw/lilToon/blob/36ff295b41cc4c398b95419d513adeecb0b322d4/Assets/lilToon/Editor/lilInspector.cs#L3731

**Comment by lilxyzw** [comment]
ご報告ありがとうございます。[0, 1]の範囲内で値をクランプするように変更を加えました。こちらの修正は次のバージョンで反映予定です。

**Comment by 0b5vr** [comment]
対応ありがとうございました！
