### ISSUE TITLE
VRChatでアバターが奇妙に透けて描画される

### ISSUE THREAD

**Issue by soramimi** [lilxyzw/lilToon#86]
lilToon 1.3.7
GeForce RTX 3060
Oculus Rift S

VRChatで、特定の条件の照明が設置されたワールドで、アバターが想定外な透け方で描画されます。

以下の手順でマテリアルを作成します。

1. 新規マテリアルを作成
2. lilToonを選択
3. 影を有効
4. 影色1の影を受け取るを1
5. 輪郭線を有効
6. VR時に非表示をオン

このマテリアルをセットしたアバターを使用し、次のワールドへ入り、鏡を見ます。
「Dark Tea Party」 https://vrchat.com/home/world/wrld_4bcbdc4a-43f0-4c23-87ea-59ab9d3baa94

この現象は、mio3ioさん制作の3Dモデル「森羅」を無改変でアップロードし、当該ワールドへ入ることでも再現できます。
ほとんどのワールドではこの問題は発生せず、ワールドの照明と影と輪郭線が互いに影響しているように思えます。

**Comment by lilxyzw** [comment]
ご報告ありがとうございます。VR時に輪郭線が非表示になる際に適切に深度が出力されない状態となっていたため、影やAmbient Occlusionの処理が適切に動作していませんでした。こちらの問題の修正は次のアップデートで反映予定です。
