### ISSUE TITLE
URP can't use Dynamic Penetration System(DPS)

### ISSUE THREAD

**Issue by jefflin0424** [lilxyzw/lilToon#90]
lilToon 1.3.7
URPにはlitoonを使用

https://twitter.com/lil_xyzw/status/1489593222988845059?lang=zh-Hant

use lilToon_DPS_1.2.9.unitypackage and RalivDynamicPenetrationSystem エラーが発生します
![image](https://github.com/lilxyzw/lilToon/assets/71255474/3f02463e-f345-4ca3-a05b-b3745fd81ac2)
![image](https://github.com/lilxyzw/lilToon/assets/71255474/202183d9-48c9-4740-be2f-c1f61c963c53)

この git で DPS を更新できることがわかりましたが、VRChat の DPS はErrorが発生すると固まってしまいます。
   Tools - DPS Shader Generator - Generate LilToon を 2 回押してGeneratorを実行すると、Errorが発生してスタックします。
https://mingyeo1ee.tistory.com/entry/VRChat-DPS-%EC%85%B0%EC%9D%B4%EB%8D%94-%EB%B3%80%EA%B2%BD-%EB%B0%A9%EB%B2%95-DPS-%EC%A0%9C%EB%84%A4%EB%A0%88%EC%9D%B4%ED%84%B0-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95

![image](https://github.com/lilxyzw/lilToon/assets/71255474/df70a18d-8541-4b38-84e1-8906a5554a6e)

**Comment by lilxyzw** [comment]
DPS is a feature heavily dependent on the built-in RP's lighting system, so it will not work with URP or HDRP.
