### ISSUE TITLE
1.4.0のFixLightingエラーが出た

### ISSUE THREAD

**Issue by TAKUHIDE** [lilxyzw/lilToon#92]
（日本人じゃないので日本語が変かもしれません）
FixLightingを押すと以下のエラーが出ます：NullReferenceException: Object reference not set to an instance of an object
lilToon.lilToonEditorUtils.FixLighting () (at Packages/jp.lilxyzw.liltoon/Editor/lilToonEditorUtils.cs:410)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)
試して1.3.7に戻すと普通にFixLightingができます
あと1.4.0は同じプロジェクトの中の 改変してないPrefabもFixLightingできます
なぜか私が改変したあとのやつだけできないです
どうやったら解決できますか？

**Comment by lilxyzw** [comment]
SkinnedMeshRendererのボーンが削除されているか空の場合にエラーとなっていたため、チェックを行うように修正しました。この修正は次のバージョンで反映されます。
