### ISSUE TITLE
Outline got big / Problem with visuals

### ISSUE THREAD

**Issue by Foxii80848** [lilxyzw/lilToon#97]
The only thing I did with the avatar is adding clothes with the CATS Blender tool. Now I wanted to add the materials again, but for some reason, the outline on the edited version of the avatar is way too big. 

<img width="1019" alt="image" src="https://github.com/lilxyzw/lilToon/assets/102874170/a5f79ce5-d936-48a8-be29-a2c67f991b43">

*Even if I just import the avatar into Blender and just export it without doing anything, it's the same with the materials.

**Comment by Foxii80848** [comment]
Fixed:

"make sure you use Apply Scalings > FBX All when exporting from blender"

**Comment by lilxyzw** [comment]
The outline scales with the avatar's scale, so if the avatar's scale is 100x, the outline will also be 100x.
